using BacklashBot.Configuration;
using BacklashBot.Helpers;
using BacklashBot.Management;
using BacklashBot.Management.Interfaces;
using BacklashBot.Services;
using BacklashBot.State.Interfaces;
using BacklashCommon.Configuration;
using BacklashCommon.Services;
using BacklashDTOs.Data;
using BacklashInterfaces.PerformanceMetrics;
using KalshiBotData.Extensions;
using KalshiBotData.Models;
using KalshiBotTests;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Options;
using Moq;

namespace BacklashBotTests
{
    /// <summary>
    /// Comprehensive unit test suite for validating the accuracy of technical indicator calculations
    /// in the TradingCalculator class. This test fixture ensures that all trading indicators
    /// (RSI, MACD, EMA, Bollinger Bands, ATR, VWAP, Stochastic Oscillator, OBV) produce
    /// mathematically correct results against known test scenarios and expected values.
    /// </summary>
    /// <remarks>
    /// The tests use predefined scenarios from TradingMetricScenarios that include both
    /// synthetic and real-world market data. Each test validates calculations against
    /// expected results with a configurable margin of error to account for floating-point
    /// precision differences. The test suite is critical for maintaining the reliability
    /// of trading signals generated by the Kalshi trading bot's strategy engine.
    /// Extension method tests have been moved to ExtensionTests.cs.
    /// </remarks>
    public class CalculationTests
    {
        /// <summary>
        /// Service for managing trading snapshot operations during testing.
        /// </summary>
        private TradingSnapshotService _snapshotService;

        /// <summary>
        /// The main calculator instance being tested for technical indicators.
        /// </summary>
        private TradingCalculator _tradingCalculator;

        /// <summary>
        /// Temporary directory path for snapshot storage during test execution.
        /// </summary>
        private string _tempSnapshotDir;

        /// <summary>
        /// Mock logger for TradingSnapshotService to capture and verify logging behavior.
        /// </summary>
        private Mock<ILogger<TradingSnapshotService>> _tradingSnapshotServiceLoggerMock;

        /// <summary>
        /// Mock logger for TradingCalculator to capture and verify logging behavior.
        /// </summary>
        private Mock<ILogger<TradingCalculator>> _tradingCalculatorLoggerMock;

        /// <summary>
        /// Real performance monitor for TradingCalculator.
        /// </summary>
        private IPerformanceMonitor _performanceMonitor;

        /// <summary>
        /// Configuration options for calculation parameters (periods, multipliers, etc.).
        /// </summary>
        private IOptions<CalculationsConfig> _calculationOptions;

        /// <summary>
        /// Configuration options for general execution parameters.
        /// </summary>
        private IOptions<GeneralExecutionConfig> _generalExecutionOptions;

        /// <summary>
        /// Margin factor used for floating-point comparison tolerance in assertions.
        /// Set to 0.1% to account for minor calculation differences.
        /// </summary>
        private double _marginFactor;

        /// <summary>
        /// Service scope factory for dependency injection during testing.
        /// </summary>
        private IServiceScopeFactory _scopeFactory;

        /// <summary>
        /// Logger for CentralPerformanceMonitor.
        /// </summary>
        private Mock<ILogger<ICentralPerformanceMonitor>> _centralPerformanceMonitorLoggerMock;

        /// <summary>
        /// Status tracker service for CentralPerformanceMonitor.
        /// </summary>
        private Mock<IStatusTrackerService> _statusTrackerServiceMock;

        /// <summary>
        /// Queue monitoring config for CentralPerformanceMonitor.
        /// </summary>
        private IOptions<QueueMonitoringConfig> _queueMonitoringOptions;

        /// <summary>
        /// Central performance monitor config for CentralPerformanceMonitor.
        /// </summary>
        private IOptions<CentralPerformanceMonitorConfig> _centralPerformanceMonitorOptions;

        /// <summary>
        /// Initializes test fixtures before each test execution.
        /// Sets up mock services, creates temporary directories, and configures
        /// the TradingCalculator instance with test-specific parameters.
        /// </summary>
        [SetUp]
        public void Setup()
        {
            _tempSnapshotDir = Path.Combine(Path.GetTempPath(), $"KalshiBotTests_{Guid.NewGuid()}");
            Directory.CreateDirectory(_tempSnapshotDir);

            _scopeFactory = new Mock<IServiceScopeFactory>().Object;
            _tradingSnapshotServiceLoggerMock = new Mock<ILogger<TradingSnapshotService>>();
            _tradingCalculatorLoggerMock = new Mock<ILogger<TradingCalculator>>();
            _centralPerformanceMonitorLoggerMock = new Mock<ILogger<ICentralPerformanceMonitor>>();
            _statusTrackerServiceMock = new Mock<IStatusTrackerService>();
            _generalExecutionOptions = TestHelper.GetGeneralExecutionConfig();
            _calculationOptions = TestHelper.GetCalculationConfig();

            // Create configs for CentralPerformanceMonitor
            _queueMonitoringOptions = Options.Create(new QueueMonitoringConfig { EnablePerformanceMetrics = false });
            _centralPerformanceMonitorOptions = Options.Create(new CentralPerformanceMonitorConfig { EnablePerformanceMetrics = true });

            // Create real CentralPerformanceMonitor
            _performanceMonitor = new CentralPerformanceMonitor(
                _centralPerformanceMonitorLoggerMock.Object,
                _generalExecutionOptions,
                "TestInstance",
                _queueMonitoringOptions,
                _centralPerformanceMonitorOptions,
                _scopeFactory,
                _statusTrackerServiceMock.Object);

            _tradingCalculator = new TradingCalculator(_tradingCalculatorLoggerMock.Object, _calculationOptions, _performanceMonitor);
            _marginFactor = 0.001; // 0.1% margin factor

            var snapshotServiceConfig = TestHelper.GetTradingSnapshotServiceConfig();
            _snapshotService = new TradingSnapshotService(_tradingSnapshotServiceLoggerMock.Object, snapshotServiceConfig, _scopeFactory, null);
        }

        /// <summary>
        /// Cleans up test fixtures after each test execution.
        /// Removes temporary directories and files created during testing.
        /// </summary>
        [TearDown]
        public void TearDown()
        {
            if (Directory.Exists(_tempSnapshotDir))
            {
                Directory.Delete(_tempSnapshotDir, true);
            }
        }


        /// <summary>
        /// Tests the Relative Strength Index (RSI) calculation accuracy across multiple scenarios.
        /// RSI measures price momentum on a 0-100 scale, with values above 70 indicating overbought
        /// conditions and below 30 indicating oversold conditions.
        /// </summary>
        /// <remarks>
        /// This test validates the RSI calculation using both synthetic and real market data scenarios.
        /// The test ensures the calculation handles edge cases and produces results within acceptable
        /// tolerance margins for floating-point precision.
        /// </remarks>
        [Test]
        public void TestRSICalculation()
        {
            TestContext.Out.WriteLine("Testing RSI calculation accuracy across multiple scenarios.");
            foreach (var scenario in TradingMetricScenarios.GetRSIScenarios())
            {
                // Arrange
                var candlesticks = scenario.Candlesticks.TakeLast(13 + 1).ToList();
                TestContext.Out.WriteLine($"Scenario: {scenario.Name}, Candlesticks Count: {candlesticks.Count}, Periods: 13");
                TestContext.Out.WriteLine($"Prices: [{string.Join(", ", candlesticks.Select(c => c.MidClose))}]");

                // Act
                var rsi = _tradingCalculator.CalculateRSI(candlesticks, 13);
                TestContext.Out.WriteLine($"Calculated RSI: {rsi}");

                // Assert
                if (!scenario.ExpectedRSI.HasValue)
                    throw new InvalidOperationException($"{scenario.Name}: Expected RSI value is null");
                var expected = scenario.ExpectedRSI.Value;
                var absoluteDiff = Math.Abs((decimal)(rsi - expected));
                var percentageDiff = expected != 0 ? (absoluteDiff / Math.Abs((decimal)(scenario.ExpectedRSI.Value))) * 100 : absoluteDiff;
                TestContext.Out.WriteLine($"{scenario.Name}: RSI Percentage Difference: {(expected != 0 ? $"{percentageDiff:F6}%" : $"Absolute Diff: {absoluteDiff:F6}")}");
                var margin = _marginFactor * Math.Abs(scenario.ExpectedRSI.Value);
                Assert.That(rsi, Is.EqualTo((double)scenario.ExpectedRSI.Value).Within(margin), $"{scenario.Name}: RSI mismatch. Expected: {expected}, Actual: {rsi}");
            }
            TestContext.Out.WriteLine("Result: All RSI calculations validated successfully.");
        }

        /// <summary>
        /// Tests the Moving Average Convergence Divergence (MACD) calculation accuracy.
        /// MACD shows the relationship between two moving averages and includes a signal line
        /// and histogram for trading signals.
        /// </summary>
        /// <remarks>
        /// Validates MACD line, signal line, and histogram calculations using comprehensive
        /// test scenarios with expected values.
        /// </remarks>
        [Test]
        public void TestMACDCalculation()
        {
            TestContext.Out.WriteLine("Testing MACD calculation accuracy.");
            foreach (var scenario in TradingMetricScenarios.GetMACDScenarios())
            {
                // Arrange
                var candlesticks = scenario.Candlesticks; // Use full 34 candlesticks for MACD

                // Act
                var (macdLine, signalLine, histogram) = _tradingCalculator.CalculateMACD(candlesticks, 12, 26, 9);

                // Assert
                if (!scenario.ExpectedMACD.macdLine.HasValue || !scenario.ExpectedMACD.signalLine.HasValue || !scenario.ExpectedMACD.histogram.HasValue)
                    throw new InvalidOperationException($"{scenario.Name}: Expected MACD values contain null");

                var expectedMacd = scenario.ExpectedMACD.macdLine.Value;
                var macdDiff = Math.Abs((decimal)(macdLine - expectedMacd));
                var macdPercentageDiff = expectedMacd != 0 ? (macdDiff / Math.Abs((decimal)(scenario.ExpectedMACD.macdLine.Value))) * 100 : macdDiff;
                TestContext.Out.WriteLine($"{scenario.Name}: MACD Line Percentage Difference: {(expectedMacd != 0 ? $"{macdPercentageDiff:F6}%" : $"Absolute Diff: {macdDiff:F6}")}");
                var macdMargin = _marginFactor * Math.Abs(scenario.ExpectedMACD.macdLine.Value);
                Assert.That(macdLine, Is.EqualTo((double)scenario.ExpectedMACD.macdLine.Value).Within(macdMargin), $"{scenario.Name}: MACD Line mismatch");

                var expectedSignal = scenario.ExpectedMACD.signalLine.Value;
                var signalDiff = Math.Abs((decimal)(signalLine - expectedSignal));
                var signalPercentageDiff = expectedSignal != 0 ? (signalDiff / Math.Abs((decimal)(scenario.ExpectedMACD.signalLine.Value))) * 100 : signalDiff;
                TestContext.Out.WriteLine($"{scenario.Name}: Signal Line Percentage Difference: {(expectedSignal != 0 ? $"{signalPercentageDiff:F6}%" : $"Absolute Diff: {signalDiff:F6}")}");
                var signalMargin = _marginFactor * Math.Abs(scenario.ExpectedMACD.signalLine.Value);
                Assert.That(signalLine, Is.EqualTo((double)scenario.ExpectedMACD.signalLine.Value).Within(signalMargin), $"{scenario.Name}: Signal Line mismatch");

                var expectedHistogram = scenario.ExpectedMACD.histogram.Value;
                var histogramDiff = Math.Abs((decimal)(histogram - expectedHistogram));
                var histogramPercentageDiff = expectedHistogram != 0 ? (histogramDiff / Math.Abs((decimal)(scenario.ExpectedMACD.histogram.Value))) * 100 : histogramDiff;
                TestContext.Out.WriteLine($"{scenario.Name}: Histogram Percentage Difference: {(expectedHistogram != 0 ? $"{histogramPercentageDiff:F6}%" : $"Absolute Diff: {histogramDiff:F6}")}");
                var histogramMargin = _marginFactor * Math.Abs(scenario.ExpectedMACD.histogram.Value);
                Assert.That(histogram, Is.EqualTo((double)scenario.ExpectedMACD.histogram.Value).Within(histogramMargin), $"{scenario.Name}: Histogram mismatch");
            }
            TestContext.Out.WriteLine("Result: All MACD calculations validated successfully.");
        }

        /// <summary>
        /// Tests the Exponential Moving Average (EMA) calculation accuracy.
        /// EMA gives more weight to recent prices, making it more responsive to price changes
        /// than simple moving averages.
        /// </summary>
        /// <remarks>
        /// Validates EMA calculations using test scenarios with expected values.
        /// </remarks>
        [Test]
        public void TestEMACalculation()
        {
            TestContext.Out.WriteLine("Testing EMA calculation accuracy.");
            foreach (var scenario in TradingMetricScenarios.GetEMAScenarios())
            {
                // Arrange
                var candlesticks = scenario.Candlesticks; // Use 5 candlesticks from source

                // Act
                var result = TradingCalculations.CalculateEMA(candlesticks.Select(c => c.MidClose).ToList(), 5);

                // Assert
                if (!scenario.ExpectedEMA.HasValue)
                    throw new InvalidOperationException($"{scenario.Name}: Expected EMA value is null");
                var expected = scenario.ExpectedEMA.Value;
                var absoluteDiff = Math.Abs((decimal)(result - expected));
                var percentageDiff = expected != 0 ? (absoluteDiff / Math.Abs((decimal)(scenario.ExpectedEMA.Value))) * 100 : absoluteDiff;
                TestContext.Out.WriteLine($"{scenario.Name}: EMA Percentage Difference: {(expected != 0 ? $"{percentageDiff:F6}%" : $"Absolute Diff: {absoluteDiff:F6}")}");
                var margin = _marginFactor * Math.Abs(scenario.ExpectedEMA.Value);
                Assert.That(result, Is.EqualTo((double)scenario.ExpectedEMA.Value).Within(margin), $"{scenario.Name}: EMA mismatch. Expected: {expected}, Actual: {result}");
            }
            TestContext.Out.WriteLine("Result: All EMA calculations validated successfully.");
        }

        /// <summary>
        /// Tests the Bollinger Bands calculation accuracy.
        /// Bollinger Bands consist of a moving average and upper/lower bands based on standard deviation,
        /// used to identify volatility and potential price reversals.
        /// </summary>
        /// <remarks>
        /// Validates middle band (SMA), upper band, and lower band calculations.
        /// </remarks>
        [Test]
        public void TestBollingerBandsCalculation()
        {
            TestContext.Out.WriteLine("Testing Bollinger Bands calculation accuracy.");
            foreach (var scenario in TradingMetricScenarios.GetBollingerBandsScenarios())
            {
                // Arrange
                var candlesticks = scenario.Candlesticks; // Use full 14 candlesticks from source

                // Act
                var (lower, middle, upper) = _tradingCalculator.CalculateBollingerBands(candlesticks, 14, 2);

                // Assert
                if (!scenario.ExpectedBollingerBands.middle.HasValue || !scenario.ExpectedBollingerBands.upper.HasValue || !scenario.ExpectedBollingerBands.lower.HasValue)
                    throw new InvalidOperationException($"{scenario.Name}: Expected Bollinger Bands values contain null");

                var expectedMiddle = scenario.ExpectedBollingerBands.middle.Value;
                var middleDiff = Math.Abs((decimal)(middle - expectedMiddle));
                var middlePercentageDiff = expectedMiddle != 0 ? (middleDiff / Math.Abs((decimal)(scenario.ExpectedBollingerBands.middle.Value))) * 100 : middleDiff;
                TestContext.Out.WriteLine($"{scenario.Name}: Middle Band Percentage Difference: {(expectedMiddle != 0 ? $"{middlePercentageDiff:F6}%" : $"Absolute Diff: {middleDiff:F6}")}");
                var middleMargin = _marginFactor * Math.Abs(scenario.ExpectedBollingerBands.middle.Value);
                Assert.That(middle, Is.EqualTo((double)scenario.ExpectedBollingerBands.middle.Value).Within(middleMargin), $"{scenario.Name}: Middle band mismatch");

                var expectedUpper = scenario.ExpectedBollingerBands.upper.Value;
                var upperDiff = Math.Abs((decimal)(upper - expectedUpper));
                var upperPercentageDiff = expectedUpper != 0 ? (upperDiff / Math.Abs((decimal)(scenario.ExpectedBollingerBands.upper.Value))) * 100 : upperDiff;
                TestContext.Out.WriteLine($"{scenario.Name}: Upper Band Percentage Difference: {(expectedUpper != 0 ? $"{upperPercentageDiff:F6}%" : $"Absolute Diff: {upperDiff:F6}")}");
                var upperMargin = _marginFactor * Math.Abs(scenario.ExpectedBollingerBands.upper.Value);
                Assert.That(upper, Is.EqualTo((double)scenario.ExpectedBollingerBands.upper.Value).Within(upperMargin), $"{scenario.Name}: Upper band mismatch");

                var expectedLower = scenario.ExpectedBollingerBands.lower.Value;
                var lowerDiff = Math.Abs((decimal)(lower - expectedLower));
                var lowerPercentageDiff = expectedLower != 0 ? (lowerDiff / Math.Abs((decimal)(scenario.ExpectedBollingerBands.lower.Value))) * 100 : lowerDiff;
                TestContext.Out.WriteLine($"{scenario.Name}: Lower Band Percentage Difference: {(expectedLower != 0 ? $"{lowerPercentageDiff:F6}%" : $"Absolute Diff: {lowerDiff:F6}")}");
                var lowerMargin = _marginFactor * Math.Abs(scenario.ExpectedBollingerBands.lower.Value);
                Assert.That(lower, Is.EqualTo((double)scenario.ExpectedBollingerBands.lower.Value).Within(lowerMargin), $"{scenario.Name}: Lower band mismatch");
            }
            TestContext.Out.WriteLine("Result: All Bollinger Bands calculations validated successfully.");
        }

        /// <summary>
        /// Tests the Average True Range (ATR) calculation accuracy.
        /// ATR measures volatility by calculating the average of true ranges over a period.
        /// Higher ATR values indicate higher volatility.
        /// </summary>
        /// <remarks>
        /// Validates ATR calculations using test scenarios with expected values.
        /// Uses one less than the full candlestick count for the period to account for historical data needs.
        /// </remarks>
        [Test]
        public void TestATRCalculation()
        {
            TestContext.Out.WriteLine("Testing ATR calculation accuracy.");
            foreach (var scenario in TradingMetricScenarios.GetATRScenarios())
            {
                // Arrange
                var candlesticks = scenario.Candlesticks; // Use full 14 candlesticks from source

                // Act
                var result = _tradingCalculator.CalculateATR(candlesticks, 13); //Use one less than full number, it needs one more for history

                // Assert
                if (!scenario.ExpectedATR.HasValue)
                    throw new InvalidOperationException($"{scenario.Name}: Expected ATR value is null");
                var expected = scenario.ExpectedATR.Value;
                var absoluteDiff = Math.Abs((decimal)(result - expected));
                var percentageDiff = expected != 0 ? (absoluteDiff / Math.Abs((decimal)(scenario.ExpectedATR.Value))) * 100 : absoluteDiff;
                TestContext.Out.WriteLine($"{scenario.Name}: ATR Percentage Difference: {(expected != 0 ? $"{percentageDiff:F6}%" : $"Absolute Diff: {absoluteDiff:F6}")}");
                var margin = _marginFactor * Math.Abs(scenario.ExpectedATR.Value);
                Assert.That(result, Is.EqualTo((double)scenario.ExpectedATR.Value).Within(margin), $"{scenario.Name}: ATR mismatch. Expected: {expected}, Actual: {result}");
            }
            TestContext.Out.WriteLine("Result: All ATR calculations validated successfully.");
        }

        /// <summary>
        /// Tests the Volume Weighted Average Price (VWAP) calculation accuracy.
        /// VWAP represents the average price weighted by volume, commonly used as a benchmark
        /// for intraday trading performance.
        /// </summary>
        /// <remarks>
        /// Validates VWAP calculations using test scenarios with price and volume data.
        /// </remarks>
        [Test]
        public void TestVWAPCalculation()
        {
            TestContext.Out.WriteLine("Testing VWAP calculation accuracy.");
            foreach (var scenario in TradingMetricScenarios.GetVWAPScenarios())
            {
                // Arrange
                var candlesticks = scenario.Candlesticks; // Use full 17 candlesticks from source

                // Act
                var result = _tradingCalculator.CalculateVWAP(candlesticks, 17);

                // Assert
                if (!scenario.ExpectedVWAP.HasValue)
                    throw new InvalidOperationException($"{scenario.Name}: Expected VWAP value is null");
                var expected = scenario.ExpectedVWAP.Value;
                var absoluteDiff = Math.Abs(result.Value - (decimal)expected);
                var percentageDiff = expected != 0 ? (absoluteDiff / Math.Abs((decimal)(scenario.ExpectedVWAP.Value))) * 100 : absoluteDiff;
                TestContext.Out.WriteLine($"{scenario.Name}: VWAP Percentage Difference: {(expected != 0 ? $"{percentageDiff:F6}%" : $"Absolute Diff: {absoluteDiff:F6}")}");
                var margin = _marginFactor * Math.Abs(scenario.ExpectedVWAP.Value);
                Assert.That((double)result.Value, Is.EqualTo(scenario.ExpectedVWAP.Value).Within(margin), $"{scenario.Name}: VWAP mismatch. Expected: {expected}, Actual: {result}");
            }
            TestContext.Out.WriteLine("Result: All VWAP calculations validated successfully.");
        }

        /// <summary>
        /// Tests the Stochastic Oscillator calculation accuracy.
        /// Stochastic Oscillator compares a closing price to its price range over a period,
        /// with %K showing current close relative to range and %D being the moving average of %K.
        /// Values above 80 indicate overbought, below 20 indicate oversold conditions.
        /// </summary>
        /// <remarks>
        /// Validates both %K and %D calculations using test scenarios.
        /// </remarks>
        [Test]
        public void TestStochasticOscillatorCalculation()
        {
            TestContext.Out.WriteLine("Testing Stochastic Oscillator calculation accuracy.");
            foreach (var scenario in TradingMetricScenarios.GetStochasticScenarios())
            {
                // Arrange
                var candlesticks = scenario.Candlesticks; // Use full 17 candlesticks from source

                // Act
                var (kResult, dResult) = _tradingCalculator.CalculateStochastic(candlesticks, 14, 3);

                // Assert
                if (!scenario.ExpectedStochastic.k.HasValue)
                    throw new InvalidOperationException($"{scenario.Name}: Expected %K value is null");
                var expectedK = scenario.ExpectedStochastic.k.Value;
                var kDiff = Math.Abs((decimal)(kResult - expectedK));
                var kPercentageDiff = expectedK != 0 ? (kDiff / Math.Abs((decimal)(scenario.ExpectedStochastic.k.Value))) * 100 : kDiff;
                TestContext.Out.WriteLine($"{scenario.Name}: %K Percentage Difference: {(expectedK != 0 ? $"{kPercentageDiff:F6}%" : $"Absolute Diff: {kDiff:F6}")}");
                var kMargin = _marginFactor * Math.Abs(scenario.ExpectedStochastic.k.Value);
                Assert.That(kResult, Is.EqualTo((double)scenario.ExpectedStochastic.k.Value).Within(kMargin), $"{scenario.Name}: %K mismatch");

                var dMargin = scenario.ExpectedStochastic.d.HasValue ? _marginFactor * Math.Abs(scenario.ExpectedStochastic.d.Value) : 0;
                if (scenario.ExpectedStochastic.d.HasValue)
                {
                    var expectedD = scenario.ExpectedStochastic.d.Value;
                    var dDiff = Math.Abs(dResult.GetValueOrDefault() - expectedD);
                    var dPercentageDiff = expectedD != 0 ? (dDiff / Math.Abs(scenario.ExpectedStochastic.d.Value)) * 100 : dDiff;
                    TestContext.Out.WriteLine($"{scenario.Name}: %D Percentage Difference: {(expectedD != 0 ? $"{dPercentageDiff:F6}%" : $"Absolute Diff: {dDiff:F6}")}");
                }
                Assert.That(dResult, Is.EqualTo(scenario.ExpectedStochastic.d.HasValue ? (double)scenario.ExpectedStochastic.d.Value : null).Within(dMargin).Or.Null, $"{scenario.Name}: %D mismatch");
            }
            TestContext.Out.WriteLine("Result: All Stochastic Oscillator calculations validated successfully.");
        }

        /// <summary>
        /// Tests the On-Balance Volume (OBV) calculation accuracy.
        /// OBV accumulates volume based on price direction - volume is added when price closes higher,
        /// subtracted when lower. Rising OBV indicates buying pressure, falling indicates selling pressure.
        /// </summary>
        /// <remarks>
        /// Validates OBV calculations using test scenarios with price and volume data.
        /// OBV is a cumulative indicator that can be positive or negative based on net volume flow.
        /// </remarks>
        [Test]
        public void TestOBVCalculation()
        {
            TestContext.Out.WriteLine("Testing OBV calculation accuracy.");
            foreach (var scenario in TradingMetricScenarios.GetOBVScenarios())
            {
                // Arrange
                var candlesticks = scenario.Candlesticks; // Use full 10 candlesticks from source

                // Act
                var result = _tradingCalculator.CalculateOBV(candlesticks);

                // Assert
                Assert.That(result, Is.EqualTo(scenario.ExpectedOBV), $"{scenario.Name}: OBV mismatch. Expected: {scenario.ExpectedOBV}, Actual: {result}");
            }
            TestContext.Out.WriteLine("Result: All OBV calculations validated successfully.");
        }
    }
}
