using BacklashDTOs;

namespace KalshiBotTests
{
    /// <summary>
    /// Provides predefined test scenarios for validating technical indicator calculations in the Kalshi trading bot.
    /// This static class serves as a comprehensive test data repository, containing synthetic and real-world market data
    /// scenarios for testing indicators such as RSI, MACD, EMA, Bollinger Bands, ATR, VWAP, Stochastic Oscillator, and OBV.
    /// Each scenario includes candlestick data and expected calculation results to ensure mathematical accuracy
    /// of trading algorithms used in the bot's strategy engine. Also provides parameterized scenario generation
    /// for custom market conditions including trending, ranging, and volatile markets.
    /// </summary>
    /// <remarks>
    /// The scenarios are designed to cover various market conditions including trending, ranging, and volatile periods.
    /// Data sources include both synthetic patterns and real AAPL (Apple Inc.) price data to ensure comprehensive testing.
    /// This class is critical for maintaining the reliability and accuracy of trading signals generated by the system.
    /// </remarks>
    public class TradingMetricScenarios
    {
        /// <summary>
        /// Represents a single test scenario containing market data and expected calculation results
        /// for validating technical indicator accuracy. Each scenario includes candlestick data
        /// and the expected outputs from various technical analysis calculations.
        /// </summary>
        public class TestScenario
        {
            /// <summary>
            /// Gets or sets the descriptive name of the test scenario, typically indicating
            /// the data source or market condition being tested.
            /// </summary>
            public string Name { get; set; }

            /// <summary>
            /// Gets or sets the list of candlestick data points used for technical analysis calculations.
            /// Each candlestick contains price and volume information for a specific time period.
            /// </summary>
            public List<PseudoCandlestick> Candlesticks { get; set; }

            /// <summary>
            /// Gets or sets the expected Relative Strength Index (RSI) value for this scenario.
            /// RSI measures price momentum on a 0-100 scale.
            /// </summary>
            public double? ExpectedRSI { get; set; }

            /// <summary>
            /// Gets or sets the expected MACD calculation results containing the MACD line,
            /// signal line, and histogram values for trend analysis.
            /// </summary>
            public (double? macdLine, double? signalLine, double? histogram) ExpectedMACD { get; set; }

            /// <summary>
            /// Gets or sets the expected Exponential Moving Average (EMA) value for this scenario.
            /// EMA gives more weight to recent prices for responsive trend analysis.
            /// </summary>
            public double? ExpectedEMA { get; set; }

            /// <summary>
            /// Gets or sets the expected Bollinger Bands calculation results containing the
            /// middle band (SMA), upper band, and lower band for volatility analysis.
            /// </summary>
            public (double? middle, double? upper, double? lower) ExpectedBollingerBands { get; set; }

            /// <summary>
            /// Gets or sets the expected Average True Range (ATR) value for volatility measurement.
            /// ATR calculates the average of true ranges over a specified period.
            /// </summary>
            public double? ExpectedATR { get; set; }

            /// <summary>
            /// Gets or sets the expected Volume Weighted Average Price (VWAP) value.
            /// VWAP represents the average price weighted by trading volume.
            /// </summary>
            public double? ExpectedVWAP { get; set; }

            /// <summary>
            /// Gets or sets the expected Stochastic Oscillator calculation results containing
            /// the %K (fast) and %D (slow) lines for momentum analysis.
            /// </summary>
            public (double? k, double? d) ExpectedStochastic { get; set; }

            /// <summary>
            /// Gets or sets the expected On-Balance Volume (OBV) value.
            /// OBV accumulates volume based on price direction to identify buying/selling pressure.
            /// </summary>
            public long? ExpectedOBV { get; set; }

            /// <summary>
            /// Validates the integrity of the test scenario data to prevent invalid test setups.
            /// </summary>
            /// <exception cref="ArgumentException">Thrown when scenario data is invalid.</exception>
            public void Validate()
            {
                if (string.IsNullOrWhiteSpace(Name))
                    throw new ArgumentException("Scenario name cannot be null or empty.", nameof(Name));

                if (Candlesticks == null || !Candlesticks.Any())
                    throw new ArgumentException("Candlesticks list cannot be null or empty.", nameof(Candlesticks));

                foreach (var candle in Candlesticks)
                {
                    if (candle == null)
                        throw new ArgumentException("Candlestick cannot be null.", nameof(Candlesticks));

                    if (candle.MidClose <= 0)
                        throw new ArgumentException("MidClose must be positive.", nameof(candle.MidClose));

                    if (candle.MidHigh < candle.MidLow)
                        throw new ArgumentException("MidHigh cannot be less than MidLow.", nameof(candle.MidHigh));

                    if (candle.Volume < 0)
                        throw new ArgumentException("Volume cannot be negative.", nameof(candle.Volume));
                }
            }
        }

        /// <summary>
        /// Retrieves test scenarios for validating Relative Strength Index (RSI) calculations.
        /// RSI measures price momentum on a 0-100 scale, with values above 70 indicating overbought
        /// conditions and below 30 indicating oversold conditions. This method provides scenarios
        /// with both synthetic data and real AAPL price data for comprehensive testing.
        /// </summary>
        /// <returns>A list of test scenarios containing candlestick data and expected RSI values.</returns>
        /// <remarks>
        /// The scenarios include:
        /// - RSI_SeekingAlpha: Synthetic data with alternating price movements
        /// - RSI_InvestExcel: Real AAPL price data for practical validation
        /// - RSI_ExtremeVolatility: Extreme price swings testing RSI in volatile conditions
        /// - RSI_TrendingUp: Steady upward trend testing RSI momentum signals
        /// - RSI_Ranging: Oscillating prices testing RSI in sideways markets
        /// </remarks>
        public static List<TestScenario> GetRSIScenarios()
        {
            var scenarios = new List<TestScenario>();
            var baseTimestamp = DateTime.Parse("2025-04-22 16:00:00");

            var rsiCandlesticks = Enumerable.Range(0, 14).Select(i => new PseudoCandlestick
            {
                Timestamp = baseTimestamp.AddHours(i),
                MidClose = 100.0 + (i % 2 == 0 ? 2.0 : -1.0),
                MidHigh = 100.5 + (i % 2 == 0 ? 2.0 : -1.0),
                MidLow = 99.5 + (i % 2 == 0 ? 2.0 : -1.0),
                Volume = 1000,
                IsFromCandlestick = true
            }).ToList();
            scenarios.Add(new TestScenario
            {
                Name = "RSI_SeekingAlpha",
                Candlesticks = rsiCandlesticks,
                ExpectedRSI = 46.15
            });

            var rsiAaplPrices = new double[] { 441.36, 439.88, 439.66, 439.19, 440.36, 441.40, 442.66, 443.82, 446.45, 447.88, 449.39, 451.00, 452.73, 454.56 };
            var rsiAaplCandlesticks = rsiAaplPrices.Select((price, i) => new PseudoCandlestick
            {
                Timestamp = baseTimestamp.AddHours(i),
                MidClose = price,
                MidHigh = price + 1.0,
                MidLow = price - 1.0,
                Volume = 1000 + i * 100,
                IsFromCandlestick = true
            }).ToList();
            scenarios.Add(new TestScenario
            {
                Name = "RSI_InvestExcel",
                Candlesticks = rsiAaplCandlesticks,
                ExpectedRSI = 87.62
            });

            // Extreme volatility scenario
            var extremeVolatilityPrices = new double[] { 100, 120, 80, 140, 60, 160, 40, 180, 20, 200, 10, 190, 30, 170 };
            var extremeVolatilityCandlesticks = extremeVolatilityPrices.Select((price, i) => new PseudoCandlestick
            {
                Timestamp = baseTimestamp.AddHours(i),
                MidClose = price,
                MidHigh = price + 10,
                MidLow = price - 10,
                Volume = 1000,
                IsFromCandlestick = true
            }).ToList();
            scenarios.Add(new TestScenario
            {
                Name = "RSI_ExtremeVolatility",
                Candlesticks = extremeVolatilityCandlesticks,
                ExpectedRSI = 95.24 // High RSI due to strong upward momentum
            });

            // Trending market scenario (uptrend)
            var trendingPrices = new double[] { 100, 102, 104, 106, 108, 110, 112, 114, 116, 118, 120, 122, 124, 126 };
            var trendingCandlesticks = trendingPrices.Select((price, i) => new PseudoCandlestick
            {
                Timestamp = baseTimestamp.AddHours(i),
                MidClose = price,
                MidHigh = price + 1,
                MidLow = price - 1,
                Volume = 1000,
                IsFromCandlestick = true
            }).ToList();
            scenarios.Add(new TestScenario
            {
                Name = "RSI_TrendingUp",
                Candlesticks = trendingCandlesticks,
                ExpectedRSI = 100 // Strong uptrend
            });

            // Ranging market scenario
            var rangingPrices = new double[] { 100, 101, 99, 102, 98, 103, 97, 104, 96, 105, 95, 106, 94, 107 };
            var rangingCandlesticks = rangingPrices.Select((price, i) => new PseudoCandlestick
            {
                Timestamp = baseTimestamp.AddHours(i),
                MidClose = price,
                MidHigh = price + 2,
                MidLow = price - 2,
                Volume = 1000,
                IsFromCandlestick = true
            }).ToList();
            scenarios.Add(new TestScenario
            {
                Name = "RSI_Ranging",
                Candlesticks = rangingCandlesticks,
                ExpectedRSI = 52.38 // Neutral RSI in ranging market
            });

            // Validate all scenarios
            foreach (var scenario in scenarios)
            {
                scenario.Validate();
            }

            return scenarios;
        }

        /// <summary>
        /// Retrieves test scenarios for validating Moving Average Convergence Divergence (MACD) calculations.
        /// MACD shows the relationship between two moving averages and includes a signal line and histogram
        /// for identifying trend changes and momentum shifts. This method provides scenarios with real AAPL
        /// price data for practical validation of MACD line, signal line, and histogram calculations.
        /// </summary>
        /// <returns>A list of test scenarios containing candlestick data and expected MACD values.</returns>
        /// <remarks>
        /// The scenarios include:
        /// - MACD_InvestExcel: Real AAPL price data covering 34 periods for comprehensive MACD testing
        /// </remarks>
        public static List<TestScenario> GetMACDScenarios()
        {
            var scenarios = new List<TestScenario>();
            var baseTimestamp = DateTime.Parse("2025-04-22 16:00:00");

            var macdPrices = new double[] { 459.99, 448.85, 444.57, 448.97, 453.28, 452.08, 451.91, 450.81, 450.30, 448.97, 447.58, 446.06, 445.52, 445.15, 441.40, 442.80, 443.66, 441.36, 439.88, 439.66, 439.19, 440.36, 441.40, 442.66, 443.82, 445.11, 446.45, 447.88, 449.39, 451.00, 452.73, 454.56, 456.50, 458.27 };
            var macdCandlesticks = macdPrices.Select((price, i) => new PseudoCandlestick
            {
                Timestamp = baseTimestamp.AddHours(i),
                MidClose = price,
                MidHigh = price + 1.0,
                MidLow = price - 1.0,
                Volume = 1000 + i * 100,
                IsFromCandlestick = true
            }).ToList();
            scenarios.Add(new TestScenario
            {
                Name = "MACD_InvestExcel",
                Candlesticks = macdCandlesticks,
                ExpectedMACD = (1.718136, -0.250365, 1.968501)
            });

            // Validate all scenarios
            foreach (var scenario in scenarios)
            {
                scenario.Validate();
            }

            return scenarios;
        }

        /// <summary>
        /// Retrieves test scenarios for validating Exponential Moving Average (EMA) calculations.
        /// EMA gives more weight to recent prices, making it more responsive to price changes
        /// than simple moving averages. This method provides scenarios with both synthetic Intel
        /// price data and real AAPL price data for comprehensive testing.
        /// </summary>
        /// <returns>A list of test scenarios containing candlestick data and expected EMA values.</returns>
        /// <remarks>
        /// The scenarios include:
        /// - EMA_Dummies: Synthetic Intel price data for basic EMA validation
        /// - EMA_InvestExcel: Real AAPL price data for practical EMA testing
        /// - EMA_ExtremeVolatility: Extreme price swings testing EMA responsiveness
        /// - EMA_TrendingUp: Steady upward trend testing EMA trend following
        /// - EMA_Ranging: Oscillating prices testing EMA stability in sideways markets
        /// </remarks>
        public static List<TestScenario> GetEMAScenarios()
        {
            var scenarios = new List<TestScenario>();
            var baseTimestamp = DateTime.Parse("2025-04-22 16:00:00");

            var intelPrices = new double[] { 22.81, 22.87, 23.03, 23.17, 23.21 };
            var emaCandlesticks = Enumerable.Range(0, 5).Select(i => new PseudoCandlestick
            {
                Timestamp = baseTimestamp.AddHours(i),
                MidClose = intelPrices[i],
                MidHigh = intelPrices[i] + 0.5,
                MidLow = intelPrices[i] - 0.5,
                Volume = 1000 + i * 100,
                IsFromCandlestick = true
            }).ToList();
            scenarios.Add(new TestScenario
            {
                Name = "EMA_Dummies",
                Candlesticks = emaCandlesticks,
                ExpectedEMA = 23.018
            });

            var emaAaplPrices = new double[] { 451.00, 452.73, 454.56, 456.50, 458.27 };
            var emaAaplCandlesticks = emaAaplPrices.Select((price, i) => new PseudoCandlestick
            {
                Timestamp = baseTimestamp.AddHours(i),
                MidClose = price,
                MidHigh = price + 1.0,
                MidLow = price - 1.0,
                Volume = 1000 + i * 100,
                IsFromCandlestick = true
            }).ToList();
            scenarios.Add(new TestScenario
            {
                Name = "EMA_InvestExcel",
                Candlesticks = emaAaplCandlesticks,
                ExpectedEMA = 454.61
            });

            // Extreme volatility scenario for EMA
            var emaExtremeVolatilityPrices = new double[] { 100, 120, 80, 140, 60 };
            var emaExtremeVolatilityCandlesticks = emaExtremeVolatilityPrices.Select((price, i) => new PseudoCandlestick
            {
                Timestamp = baseTimestamp.AddHours(i),
                MidClose = price,
                MidHigh = price + 5,
                MidLow = price - 5,
                Volume = 1000,
                IsFromCandlestick = true
            }).ToList();
            scenarios.Add(new TestScenario
            {
                Name = "EMA_ExtremeVolatility",
                Candlesticks = emaExtremeVolatilityCandlesticks,
                ExpectedEMA = 100.0 // EMA reacts to volatility
            });

            // Trending market scenario for EMA
            var emaTrendingPrices = new double[] { 100, 102, 104, 106, 108 };
            var emaTrendingCandlesticks = emaTrendingPrices.Select((price, i) => new PseudoCandlestick
            {
                Timestamp = baseTimestamp.AddHours(i),
                MidClose = price,
                MidHigh = price + 1,
                MidLow = price - 1,
                Volume = 1000,
                IsFromCandlestick = true
            }).ToList();
            scenarios.Add(new TestScenario
            {
                Name = "EMA_TrendingUp",
                Candlesticks = emaTrendingCandlesticks,
                ExpectedEMA = 104.0 // EMA follows uptrend
            });

            // Ranging market scenario for EMA
            var emaRangingPrices = new double[] { 100, 101, 99, 102, 98 };
            var emaRangingCandlesticks = emaRangingPrices.Select((price, i) => new PseudoCandlestick
            {
                Timestamp = baseTimestamp.AddHours(i),
                MidClose = price,
                MidHigh = price + 2,
                MidLow = price - 2,
                Volume = 1000,
                IsFromCandlestick = true
            }).ToList();
            scenarios.Add(new TestScenario
            {
                Name = "EMA_Ranging",
                Candlesticks = emaRangingCandlesticks,
                ExpectedEMA = 100.0 // EMA remains stable in ranging market
            });

            // Validate all scenarios
            foreach (var scenario in scenarios)
            {
                scenario.Validate();
            }

            return scenarios;
        }

        /// <summary>
        /// Retrieves test scenarios for validating Bollinger Bands calculations.
        /// Bollinger Bands consist of a moving average and upper/lower bands based on standard deviation,
        /// used to identify volatility and potential price reversals. This method provides scenarios
        /// with both synthetic data and real AAPL price data for comprehensive testing.
        /// </summary>
        /// <returns>A list of test scenarios containing candlestick data and expected Bollinger Bands values.</returns>
        /// <remarks>
        /// The scenarios include:
        /// - Bollinger_Investopedia: Synthetic data demonstrating standard Bollinger Band calculations
        /// - Bollinger_InvestExcel: Real AAPL price data for practical validation (approximate values based on SMA and volatility)
        /// </remarks>
        public static List<TestScenario> GetBollingerBandsScenarios()
        {
            var scenarios = new List<TestScenario>();
            var baseTimestamp = DateTime.Parse("2025-04-22 16:00:00");

            var bollingerPrices = new double[] { 10, 11, 12, 11, 14, 13, 12, 11, 10, 12, 13, 14, 12, 11 };
            var bollingerCandlesticks = bollingerPrices.Select((price, i) => new PseudoCandlestick
            {
                Timestamp = baseTimestamp.AddHours(i),
                MidClose = price,
                MidHigh = price + 1,
                MidLow = price - 1,
                Volume = 1000,
                IsFromCandlestick = true
            }).ToList();
            scenarios.Add(new TestScenario
            {
                Name = "Bollinger_Investopedia",
                Candlesticks = bollingerCandlesticks,
                ExpectedBollingerBands = (11.86, 14.35, 9.37)
            });

            var bollingerAaplPrices = new double[] { 441.36, 439.88, 439.66, 439.19, 440.36, 441.40, 442.66, 443.82, 446.45, 447.88, 449.39, 451.00, 452.73, 454.56 };
            var bollingerAaplCandlesticks = bollingerAaplPrices.Select((price, i) => new PseudoCandlestick
            {
                Timestamp = baseTimestamp.AddHours(i),
                MidClose = price,
                MidHigh = price + 1.0,
                MidLow = price - 1.0,
                Volume = 1000 + i * 100,
                IsFromCandlestick = true
            }).ToList();
            scenarios.Add(new TestScenario
            {
                Name = "Bollinger_InvestExcel",
                Candlesticks = bollingerAaplCandlesticks,
                ExpectedBollingerBands = (445.0, 455.0, 435.0) // Approximate, based on SMA and volatility
            });

            // Validate all scenarios
            foreach (var scenario in scenarios)
            {
                scenario.Validate();
            }

            return scenarios;
        }

        /// <summary>
        /// Retrieves test scenarios for validating Average True Range (ATR) calculations.
        /// ATR measures volatility by calculating the average of true ranges over a period.
        /// Higher ATR values indicate higher volatility. This method provides scenarios
        /// with both synthetic data and real AAPL price data for comprehensive testing.
        /// </summary>
        /// <returns>A list of test scenarios containing candlestick data and expected ATR values.</returns>
        /// <remarks>
        /// The scenarios include:
        /// - ATR_Investopedia: Synthetic high-low-close data demonstrating ATR calculations
        /// - ATR_InvestExcel: Real AAPL price data for practical ATR validation
        /// </remarks>
        public static List<TestScenario> GetATRScenarios()
        {
            var scenarios = new List<TestScenario>();
            var baseTimestamp = DateTime.Parse("2025-04-22 16:00:00");

            var atrData = new (double high, double low, double close)[]
            {
                (51, 49, 50), (52, 50, 51), (53, 51, 52), (53, 51, 52),
                (52, 50, 51), (51, 49, 50), (52, 50, 51), (53, 51, 52),
                (54, 52, 53), (54, 52, 53), (53, 51, 52), (52, 50, 51),
                (53, 51, 52), (53, 51, 52)
            };
            var atrCandlesticks = atrData.Select((data, i) => new PseudoCandlestick
            {
                Timestamp = baseTimestamp.AddHours(i),
                MidClose = data.close,
                MidHigh = data.high,
                MidLow = data.low,
                Volume = 1000,
                IsFromCandlestick = true
            }).ToList();
            scenarios.Add(new TestScenario
            {
                Name = "ATR_Investopedia",
                Candlesticks = atrCandlesticks,
                ExpectedATR = 2
            });

            var atrAaplPrices = new (double high, double low, double close)[]
            {
                (442.36, 440.36, 441.36), (440.88, 438.88, 439.88), (440.66, 438.66, 439.66),
                (440.19, 438.19, 439.19), (441.36, 439.36, 440.36), (442.40, 440.40, 441.40),
                (443.66, 441.66, 442.66), (444.82, 442.82, 443.82), (447.45, 445.45, 446.45),
                (448.88, 446.88, 447.88), (450.39, 448.39, 449.39), (452.00, 450.00, 451.00),
                (453.73, 451.73, 452.73), (455.56, 453.56, 454.56)
            };
            var atrAaplCandlesticks = atrAaplPrices.Select((data, i) => new PseudoCandlestick
            {
                Timestamp = baseTimestamp.AddHours(i),
                MidClose = data.close,
                MidHigh = data.high,
                MidLow = data.low,
                Volume = 1000 + i * 100,
                IsFromCandlestick = true
            }).ToList();
            scenarios.Add(new TestScenario
            {
                Name = "ATR_InvestExcel",
                Candlesticks = atrAaplCandlesticks,
                ExpectedATR = 2.45
            });

            // Validate all scenarios
            foreach (var scenario in scenarios)
            {
                scenario.Validate();
            }

            return scenarios;
        }

        /// <summary>
        /// Retrieves test scenarios for validating Volume Weighted Average Price (VWAP) calculations.
        /// VWAP represents the average price weighted by volume, commonly used as a benchmark
        /// for intraday trading performance. This method provides scenarios with price and volume
        /// data for comprehensive VWAP testing across different market conditions.
        /// </summary>
        /// <returns>A list of test scenarios containing candlestick data and expected VWAP values.</returns>
        /// <remarks>
        /// The scenarios include:
        /// - VWAP_Investing: Synthetic data with varying volume levels
        /// - VWAP_InvestExcel: Real AAPL price and volume data
        /// - VWAP_Stable: Stable price data to test VWAP calculation consistency
        /// </remarks>
        public static List<TestScenario> GetVWAPScenarios()
        {
            var scenarios = new List<TestScenario>();
            var baseTimestamp = DateTime.Parse("2025-04-22 16:00:00");

            var vwapData = new (double high, double low, double close, int volume)[]
            {
                (150.39, 150.22, 150.31, 380),
                (150.47, 150.38, 150.41, 5270),
                (150.41, 150.31, 150.36, 1000),
                (150.41, 150.31, 150.36, 1000),
                (150.41, 150.31, 150.36, 1000),
                (150.41, 150.31, 150.36, 1000),
                (150.41, 150.31, 150.36, 1000),
                (150.41, 150.31, 150.36, 1000),
                (150.41, 150.31, 150.36, 1000),
                (150.41, 150.31, 150.36, 1000),
                (150.41, 150.31, 150.36, 1000),
                (150.41, 150.31, 150.36, 1000),
                (150.41, 150.31, 450.36, 1000),
                (150.41, 150.31, 150.36, 1000),
                (150.41, 150.31, 150.36, 1000),
                (150.41, 150.31, 150.36, 1000),
                (150.41, 150.31, 150.36, 1000)
            };
            var vwapCandlesticks = vwapData.Select((data, i) => new PseudoCandlestick
            {
                Timestamp = baseTimestamp.AddMinutes(i),
                MidClose = data.close,
                MidHigh = data.high,
                MidLow = data.low,
                Volume = data.volume,
                IsFromCandlestick = true
            }).ToList();
            scenarios.Add(new TestScenario
            {
                Name = "VWAP_Investing",
                Candlesticks = vwapCandlesticks,
                ExpectedVWAP = 155.22
            });

            var vwapAaplPrices = new (double high, double low, double close, int volume)[]
            {
                (442.36, 440.36, 441.36, 1000), (440.88, 438.88, 439.88, 1100),
                (440.66, 438.66, 439.66, 1200), (440.19, 438.19, 439.19, 1300),
                (441.36, 439.36, 440.36, 1400), (442.40, 440.40, 441.40, 1500),
                (443.66, 441.66, 442.66, 1600), (444.82, 442.82, 443.82, 1700),
                (447.45, 445.45, 446.45, 1800), (448.88, 446.88, 447.88, 1900),
                (450.39, 448.39, 449.39, 2000), (452.00, 450.00, 451.00, 2100),
                (453.73, 451.73, 452.73, 2200), (455.56, 453.56, 454.56, 2300),
                (457.50, 455.50, 456.50, 2400), (459.27, 457.27, 458.27, 2500),
                (458.27, 456.27, 458.27, 2600)
            };
            var vwapAaplCandlesticks = vwapAaplPrices.Select((data, i) => new PseudoCandlestick
            {
                Timestamp = baseTimestamp.AddHours(i),
                MidClose = data.close,
                MidHigh = data.high,
                MidLow = data.low,
                Volume = data.volume,
                IsFromCandlestick = true
            }).ToList();
            scenarios.Add(new TestScenario
            {
                Name = "VWAP_InvestExcel",
                Candlesticks = vwapAaplCandlesticks,
                ExpectedVWAP = 449.0
            });

            var vwapStableData = new (double high, double low, double close, int volume)[]
            {
                (100.0, 99.0, 99.5, 500),
                (101.0, 99.5, 100.0, 1000),
                (100.5, 99.5, 100.0, 1000),
                (100.5, 99.5, 100.0, 1000),
                (100.5, 99.5, 100.0, 1000)
            };

            var vwapStableCandlesticks = vwapStableData.Select((data, i) => new PseudoCandlestick
            {
                Timestamp = baseTimestamp.AddMinutes(i),
                MidClose = data.close,
                MidHigh = data.high,
                MidLow = data.low,
                Volume = data.volume,
                IsFromCandlestick = true
            }).ToList();

            scenarios.Add(new TestScenario
            {
                Name = "VWAP_Stable",
                Candlesticks = vwapStableCandlesticks,
                ExpectedVWAP = 99.94
            });

            // Validate all scenarios
            foreach (var scenario in scenarios)
            {
                scenario.Validate();
            }

            return scenarios;
        }

        /// <summary>
        /// Retrieves test scenarios for validating Stochastic Oscillator calculations.
        /// The Stochastic Oscillator compares a closing price to its price range over a period,
        /// with %K showing current close relative to range and %D being the moving average of %K.
        /// Values above 80 indicate overbought, below 20 indicate oversold conditions.
        /// This method provides scenarios with both synthetic and real market data.
        /// </summary>
        /// <returns>A list of test scenarios containing candlestick data and expected Stochastic values.</returns>
        /// <remarks>
        /// The scenarios include:
        /// - Stochastic_Investopedia: Synthetic data with constant high/low range
        /// - Stochastic_Varying: Synthetic data with varying price ranges
        /// - Stochastic_Realistic: Real AAPL price data for comprehensive testing
        /// - Stochastic_Middle: Synthetic data testing mid-range conditions
        /// </remarks>
        public static List<TestScenario> GetStochasticScenarios()
        {
            var scenarios = new List<TestScenario>();
            var baseTimestamp = DateTime.Parse("2025-04-22 16:00:00");

            var stochasticCandlesticks = Enumerable.Repeat(new PseudoCandlestick
            {
                Timestamp = baseTimestamp,
                MidClose = 145,
                MidHigh = 150,
                MidLow = 125,
                Volume = 1000,
                IsFromCandlestick = true
            }, 17).Select((c, i) => { c.Timestamp = baseTimestamp.AddHours(i); return c; }).ToList();
            scenarios.Add(new TestScenario
            {
                Name = "Stochastic_Investopedia",
                Candlesticks = stochasticCandlesticks,
                ExpectedStochastic = (80.0, 80.0)
            });


            baseTimestamp = DateTime.Parse("2025-04-22 16:00:00");

            var stochasticVaryingCandlesticks = new (double high, double low, double close)[]
            {
            (10.5, 9.5, 10.0),
            (10.8, 9.8, 10.6),
            (11.0, 10.0, 10.8),
            (11.2, 10.2, 11.1),
            (11.4, 10.4, 11.3),
            (11.5, 10.5, 11.0),
            (11.3, 10.3, 10.9),
            (11.2, 10.2, 10.5),
            (11.0, 10.0, 10.2),
            (10.8, 9.8, 10.0),
            (10.7, 9.7, 9.9),
            (10.5, 9.5, 9.7),
            (10.3, 9.3, 9.5),
            (10.2, 9.2, 9.4),
            (10.0, 9.0, 9.2),
            (10.3, 9.3, 9.8),
            (10.5, 9.5, 10.2)
            }.Select((data, i) => new PseudoCandlestick
            {
                Timestamp = baseTimestamp.AddHours(i),
                MidClose = data.close,
                MidHigh = data.high,
                MidLow = data.low,
                Volume = 1000,
                IsFromCandlestick = true
            }).ToList();

            scenarios.Add(new TestScenario
            {
                Name = "Stochastic_Varying",
                Candlesticks = stochasticVaryingCandlesticks,
                ExpectedStochastic = (48.0, 29.33)
            });
            var stochasticRealisticCandlesticks = new (double high, double low, double close)[]
                {
                    (50.5, 49.5, 50.0), (50.8, 49.8, 50.6), (51.0, 50.0, 50.8), (51.2, 50.2, 51.1), (51.4, 50.4, 51.3),
                    (51.5, 50.5, 51.0), (51.3, 50.3, 50.9), (51.2, 50.2, 50.5), (51.0, 50.0, 50.2), (50.8, 49.8, 50.0),
                    (50.7, 49.7, 49.9), (50.5, 49.5, 49.7), (50.3, 49.3, 49.5), (50.2, 49.2, 49.4), (50.0, 49.0, 49.2),
                    (50.3, 49.3, 49.8), (50.5, 49.5, 50.2), (50.7, 49.7, 50.6), (51.0, 50.0, 50.9), (51.2, 50.2, 51.0),
                    (51.5, 50.5, 51.3), (51.7, 50.7, 51.5), (51.8, 50.8, 51.7), (52.0, 51.0, 52.0), (52.3, 51.3, 52.2),
                    (52.5, 51.5, 52.4), (52.7, 51.7, 52.6), (52.8, 51.8, 52.5), (52.6, 51.6, 52.3), (52.5, 51.5, 52.0),
                    (52.3, 51.3, 51.8), (52.2, 51.2, 51.7), (52.0, 51.0, 51.5), (51.8, 50.8, 51.2), (51.7, 50.7, 51.0),
                    (51.5, 50.5, 50.8), (51.2, 50.2, 50.6), (51.0, 50.0, 50.3), (50.8, 49.8, 50.0), (50.5, 49.5, 49.8),
                    (50.3, 49.3, 49.5), (50.0, 49.0, 49.3), (49.8, 48.8, 49.0), (49.6, 48.6, 48.8), (49.5, 48.5, 48.5),
                    (49.3, 48.3, 48.3), (49.0, 48.0, 48.0), (48.8, 47.8, 47.8), (48.5, 47.5, 47.5), (48.3, 47.3, 47.3)
                }.Select((data, i) => new PseudoCandlestick
                {
                    Timestamp = baseTimestamp.AddHours(i),
                    MidClose = data.close,
                    MidHigh = data.high,
                    MidLow = data.low,
                    Volume = 1000,
                    IsFromCandlestick = true
                }).ToList();

            scenarios.Add(new TestScenario
            {
                Name = "Stochastic_Realistic",
                Candlesticks = stochasticRealisticCandlesticks,
                ExpectedStochastic = (0, 0)
            });
            var stochasticMiddleCandlesticks = new (double high, double low, double close)[]
                {
                    (50.5, 49.5, 50.0), (51.0, 50.0, 50.5), (51.5, 50.5, 51.0), (52.0, 51.0, 51.5), (52.5, 51.5, 52.0),
                    (52.0, 51.0, 51.5), (51.5, 50.5, 51.0), (51.0, 50.0, 50.5), (50.5, 49.5, 50.0), (50.0, 49.0, 49.5),
                    (50.5, 49.5, 50.0), (51.0, 50.0, 50.5), (51.5, 50.5, 51.0), (52.0, 51.0, 51.5), (52.5, 51.5, 52.0),
                    (52.0, 51.0, 51.5), (51.5, 50.5, 51.0), (51.0, 50.0, 50.5), (50.5, 49.5, 50.0), (50.0, 49.0, 49.5),
                    (49.5, 48.5, 49.0), (49.0, 48.0, 48.5), (48.5, 47.5, 48.0), (48.0, 47.0, 47.5), (48.5, 47.5, 48.0),
                    (49.0, 48.0, 48.5), (49.5, 48.5, 49.0), (50.0, 49.0, 49.5), (50.5, 49.5, 50.0), (51.0, 50.0, 50.5),
                    (51.5, 50.5, 51.0), (52.0, 51.0, 51.5), (52.5, 51.5, 52.0), (52.0, 51.0, 51.5), (51.5, 50.5, 51.0),
                    (51.0, 50.0, 50.5), (50.5, 49.5, 50.0), (50.0, 49.0, 49.5), (49.5, 48.5, 49.0), (49.0, 48.0, 48.5),
                    (48.5, 47.5, 48.0), (48.0, 47.0, 47.5), (47.5, 46.5, 47.0), (47.0, 46.0, 46.5), (47.5, 46.5, 47.0),
                    (48.0, 47.0, 47.5), (48.5, 47.5, 48.0), (49.0, 48.0, 48.5), (49.5, 48.5, 49.0), (50.0, 49.0, 49.5)
                }.Select((data, i) => new PseudoCandlestick
                {
                    Timestamp = baseTimestamp.AddHours(i),
                    MidClose = data.close,
                    MidHigh = data.high,
                    MidLow = data.low,
                    Volume = 1000,
                    IsFromCandlestick = true
                }).ToList();

            scenarios.Add(new TestScenario
            {
                Name = "Stochastic_Middle",
                Candlesticks = stochasticMiddleCandlesticks,
                ExpectedStochastic = (77.78, 61.08)
            });

            // Validate all scenarios
            foreach (var scenario in scenarios)
            {
                scenario.Validate();
            }

            return scenarios;
        }

        /// <summary>
        /// Retrieves test scenarios for validating On-Balance Volume (OBV) calculations.
        /// OBV accumulates volume based on price direction - volume is added when price closes higher,
        /// subtracted when lower. Rising OBV indicates buying pressure, falling indicates selling pressure.
        /// This method provides scenarios with both synthetic and real AAPL price/volume data.
        /// </summary>
        /// <returns>A list of test scenarios containing candlestick data and expected OBV values.</returns>
        /// <remarks>
        /// The scenarios include:
        /// - OBV_IG: Synthetic data demonstrating OBV accumulation patterns
        /// - OBV_InvestExcel: Real AAPL price and volume data for practical validation
        /// </remarks>
        public static List<TestScenario> GetOBVScenarios()
        {
            var scenarios = new List<TestScenario>();
            var baseTimestamp = DateTime.Parse("2025-04-22 16:00:00");

            var obvData = new (double close, int volume)[]
            {
                (100, 10000),
                (105, 14000),
                (110, 12000),
                (102, 10000),
                (99, 6000),
                (120, 27000),
                (117, 17000),
                (114, 14000),
                (110, 10000),
                (102, 8000)
            };
            var obvCandlesticks = obvData.Select((data, i) => new PseudoCandlestick
            {
                Timestamp = baseTimestamp.AddHours(i),
                MidClose = data.close,
                MidHigh = data.close + 1,
                MidLow = data.close - 1,
                Volume = data.volume,
                IsFromCandlestick = true
            }).ToList();
            scenarios.Add(new TestScenario
            {
                Name = "OBV_IG",
                Candlesticks = obvCandlesticks,
                ExpectedOBV = -12000
            });

            var obvAaplData = new (double close, int volume)[]
            {
                (446.45, 1800), (447.88, 1900), (449.39, 2000), (451.00, 2100),
                (452.73, 2200), (454.56, 2300), (456.50, 2400), (458.27, 2500),
                (458.27, 2600), (458.27, 2700)
            };
            var obvAaplCandlesticks = obvAaplData.Select((data, i) => new PseudoCandlestick
            {
                Timestamp = baseTimestamp.AddHours(i),
                MidClose = data.close,
                MidHigh = data.close + 1.0,
                MidLow = data.close - 1.0,
                Volume = data.volume,
                IsFromCandlestick = true
            }).ToList();
            scenarios.Add(new TestScenario
            {
                Name = "OBV_InvestExcel",
                Candlesticks = obvAaplCandlesticks,
                ExpectedOBV = 15400
            });

            // Validate all scenarios
            foreach (var scenario in scenarios)
            {
                scenario.Validate();
            }

            return scenarios;

        }

        /// <summary>
        /// Generates a parameterized test scenario based on specified market conditions.
        /// This method supports different market types: "trending", "ranging", "volatile".
        /// </summary>
        /// <param name="marketType">The type of market condition ("trending", "ranging", "volatile").</param>
        /// <param name="periods">Number of periods to generate (default 14).</param>
        /// <param name="basePrice">Starting price (default 100).</param>
        /// <param name="volatility">Volatility factor (default 1.0).</param>
        /// <param name="trendStrength">Trend strength for trending markets (default 0.5).</param>
        /// <returns>A custom TestScenario with generated data.</returns>
        public static TestScenario GenerateCustomScenario(string marketType, int periods = 14, double basePrice = 100.0, double volatility = 1.0, double trendStrength = 0.5)
        {
            if (string.IsNullOrWhiteSpace(marketType))
                throw new ArgumentException("Market type cannot be null or empty.", nameof(marketType));

            if (periods < 1)
                throw new ArgumentException("Periods must be at least 1.", nameof(periods));

            if (basePrice <= 0)
                throw new ArgumentException("Base price must be positive.", nameof(basePrice));

            var baseTimestamp = DateTime.Parse("2025-04-22 16:00:00");
            var prices = new List<double>();
            var random = new Random(42); // Fixed seed for reproducible results

            for (int i = 0; i < periods; i++)
            {
                double price;
                switch (marketType.ToLower())
                {
                    case "trending":
                        // Linear trend with some noise
                        price = basePrice + (i * trendStrength) + (random.NextDouble() - 0.5) * volatility * 2;
                        break;
                    case "ranging":
                        // Oscillating within a range
                        price = basePrice + Math.Sin(i * 0.5) * volatility * 5 + (random.NextDouble() - 0.5) * volatility;
                        break;
                    case "volatile":
                        // High volatility with random walks
                        price = basePrice + (random.NextDouble() - 0.5) * volatility * 10;
                        if (i > 0) price += prices[i - 1] * 0.1; // Some momentum
                        break;
                    default:
                        throw new ArgumentException($"Unsupported market type: {marketType}. Use 'trending', 'ranging', or 'volatile'.", nameof(marketType));
                }
                prices.Add(Math.Max(price, 0.01)); // Ensure positive price
            }

            var candlesticks = prices.Select((price, i) => new PseudoCandlestick
            {
                Timestamp = baseTimestamp.AddHours(i),
                MidClose = price,
                MidHigh = price + volatility,
                MidLow = Math.Max(price - volatility, 0.01),
                Volume = 1000 + random.Next(1000),
                IsFromCandlestick = true
            }).ToList();

            var scenario = new TestScenario
            {
                Name = $"{marketType}_{periods}periods_{basePrice}base_{volatility}vol",
                Candlesticks = candlesticks
            };

            scenario.Validate();
            return scenario;
        }
    }
}
