using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Options;
using Moq;
using BacklashBot.Helpers;
using BacklashBot.Services;
using TradingStrategies.Configuration;
using KalshiBotData.Extensions;
using KalshiBotData.Models;
using BacklashDTOs.Data;
using System.Collections.Generic;

namespace KalshiBotTests
{
    /// <summary>
    /// Comprehensive unit test suite for validating the accuracy of technical indicator calculations
    /// in the TradingCalculator class. This test fixture ensures that all trading indicators
    /// (RSI, MACD, EMA, Bollinger Bands, ATR, VWAP, Stochastic Oscillator, OBV) produce
    /// mathematically correct results against known test scenarios and expected values.
    /// </summary>
    /// <remarks>
    /// The tests use predefined scenarios from TradingMetricScenarios that include both
    /// synthetic and real-world market data. Each test validates calculations against
    /// expected results with a configurable margin of error to account for floating-point
    /// precision differences. The test suite is critical for maintaining the reliability
    /// of trading signals generated by the Kalshi trading bot's strategy engine.
    /// </remarks>
    public class CalculationTests
    {
        /// <summary>
        /// Service for managing trading snapshot operations during testing.
        /// </summary>
        private TradingSnapshotService _snapshotService;

        /// <summary>
        /// The main calculator instance being tested for technical indicators.
        /// </summary>
        private TradingCalculator _tradingCalculator;

        /// <summary>
        /// Temporary directory path for snapshot storage during test execution.
        /// </summary>
        private string _tempSnapshotDir;

        /// <summary>
        /// Mock logger for TradingSnapshotService to capture and verify logging behavior.
        /// </summary>
        private Mock<ILogger<TradingSnapshotService>> _tradingSnapshotServiceLoggerMock;

        /// <summary>
        /// Mock logger for TradingCalculator to capture and verify logging behavior.
        /// </summary>
        private Mock<ILogger<TradingCalculator>> _tradingCalculatorLoggerMock;

        /// <summary>
        /// Configuration options for snapshot service behavior.
        /// </summary>
        private IOptions<SnapshotConfig> _snapshotOptions;

        /// <summary>
        /// Configuration options for calculation parameters (periods, multipliers, etc.).
        /// </summary>
        private IOptions<CalculationConfig> _calculationOptions;

        /// <summary>
        /// Configuration options for trading parameters and thresholds.
        /// </summary>
        private IOptions<TradingConfig> _tradingOptions;

        /// <summary>
        /// Margin factor used for floating-point comparison tolerance in assertions.
        /// Set to 0.1% to account for minor calculation differences.
        /// </summary>
        private double _marginFactor;

        /// <summary>
        /// Service scope factory for dependency injection during testing.
        /// </summary>
        private IServiceScopeFactory _scopeFactory;

        /// <summary>
        /// Initializes test fixtures before each test execution.
        /// Sets up mock services, creates temporary directories, and configures
        /// the TradingCalculator instance with test-specific parameters.
        /// </summary>
        [SetUp]
        public void Setup()
        {
            _tempSnapshotDir = Path.Combine(Path.GetTempPath(), $"KalshiBotTests_{Guid.NewGuid()}");
            Directory.CreateDirectory(_tempSnapshotDir);

            _scopeFactory = new Mock<IServiceScopeFactory>().Object;
            _tradingSnapshotServiceLoggerMock = new Mock<ILogger<TradingSnapshotService>>();
            _tradingCalculatorLoggerMock = new Mock<ILogger<TradingCalculator>>();
            _tradingCalculator = new TradingCalculator(_tradingCalculatorLoggerMock.Object, _calculationOptions.Value);
            _tradingOptions = TestHelper.GetTradingConfig();
            _calculationOptions = TestHelper.GetCalculationConfig();
            _marginFactor = 0.001; // 0.1% margin factor

            _snapshotService = new TradingSnapshotService(_tradingSnapshotServiceLoggerMock.Object, _snapshotOptions, _tradingOptions, _scopeFactory);
        }

        /// <summary>
        /// Cleans up test fixtures after each test execution.
        /// Removes temporary directories and files created during testing.
        /// </summary>
        [TearDown]
        public void TearDown()
        {
            if (Directory.Exists(_tempSnapshotDir))
            {
                Directory.Delete(_tempSnapshotDir, true);
            }
        }

        #region Extension Method Tests

        /// <summary>
        /// Tests AnnouncementExtensions for null parameter validation and transformation accuracy.
        /// </summary>
        [Test]
        public void TestAnnouncementExtensions()
        {
            // Test null parameter validation
            Assert.Throws<ArgumentNullException>(() => ((Announcement)null).ToAnnouncementDTO());
            Assert.Throws<ArgumentNullException>(() => ((AnnouncementDTO)null).ToAnnouncement());
            Assert.Throws<ArgumentNullException>(() => ((Announcement)null).UpdateAnnouncement(new AnnouncementDTO()));
            Assert.Throws<ArgumentNullException>(() => new Announcement { Message = "test", Status = "test", Type = "test" }.UpdateAnnouncement(null));

            // Test transformation accuracy
            var originalAnnouncement = new Announcement
            {
                AnnouncementID = 123,
                DeliveryTime = DateTime.UtcNow,
                Message = "Test Message",
                Status = "Active",
                Type = "Info",
                CreatedDate = DateTime.UtcNow.AddDays(-1),
                LastModifiedDate = DateTime.UtcNow.AddDays(-1)
            };

            var dto = originalAnnouncement.ToAnnouncementDTO();
            var reconstructed = dto.ToAnnouncement();

            Assert.That(reconstructed.AnnouncementID, Is.EqualTo(originalAnnouncement.AnnouncementID));
            Assert.That(reconstructed.Message, Is.EqualTo(originalAnnouncement.Message));
            Assert.That(reconstructed.Status, Is.EqualTo(originalAnnouncement.Status));
            Assert.That(reconstructed.Type, Is.EqualTo(originalAnnouncement.Type));

            // Test update functionality
            var updateDTO = new AnnouncementDTO
            {
                AnnouncementID = 123,
                Message = "Updated Message",
                Status = "Inactive",
                Type = "Warning",
                DeliveryTime = DateTime.UtcNow,
                CreatedDate = originalAnnouncement.CreatedDate,
                LastModifiedDate = originalAnnouncement.LastModifiedDate
            };

            var updated = originalAnnouncement.UpdateAnnouncement(updateDTO);
            Assert.That(updated.Message, Is.EqualTo("Updated Message"));
            Assert.That(updated.Status, Is.EqualTo("Inactive"));
            Assert.That(updated.Type, Is.EqualTo("Warning"));

            // Test batch transformations
            var announcements = new List<Announcement> { originalAnnouncement, originalAnnouncement };
            var dtos = announcements.ToAnnouncementDTOs();
            var reconstructedList = dtos.ToAnnouncements();

            Assert.That(reconstructedList.Count, Is.EqualTo(2));
            Assert.That(reconstructedList[0].AnnouncementID, Is.EqualTo(originalAnnouncement.AnnouncementID));

            // Test deep clone
            var cloned = originalAnnouncement.DeepClone();
            Assert.That(cloned.AnnouncementID, Is.EqualTo(originalAnnouncement.AnnouncementID));
            Assert.That(cloned, Is.Not.SameAs(originalAnnouncement)); // Different object references

            var clonedDTO = dto.DeepClone();
            Assert.That(clonedDTO.AnnouncementID, Is.EqualTo(dto.AnnouncementID));
            Assert.That(clonedDTO, Is.Not.SameAs(dto)); // Different object references

            // Test performance metrics collection
            var metrics = AnnouncementExtensions.GetPerformanceMetrics();
            Assert.That(metrics, Is.Not.Null);
            Assert.That(metrics.ContainsKey("ToAnnouncementDTO"), Is.True);
        }

        /// <summary>
        /// Tests BrainInstanceExtensions for null parameter validation and transformation accuracy.
        /// </summary>
        [Test]
        public void TestBrainInstanceExtensions()
        {
            // Test null parameter validation
            Assert.Throws<ArgumentNullException>(() => ((BrainInstance)null).ToBrainInstanceDTO());
            Assert.Throws<ArgumentNullException>(() => ((BrainInstanceDTO)null).ToBrainInstance());
            Assert.Throws<ArgumentNullException>(() => ((BrainInstance)null).UpdateBrainInstance(new BrainInstanceDTO()));
            Assert.Throws<ArgumentNullException>(() => new BrainInstance().UpdateBrainInstance(null));

            // Test transformation accuracy
            var testGuid = Guid.NewGuid();
            var originalBrainInstance = new BrainInstance
            {
                BrainInstanceName = "TestBrain",
                WatchPositions = true,
                WatchOrders = false,
                ManagedWatchList = true,
                TargetWatches = 5,
                BrainLock = testGuid,
                UsageMin = 10,
                UsageMax = 100,
                CaptureSnapshots = true,
                MinimumInterest = 0.5,
                LastSeen = DateTime.UtcNow
            };

            var dto = originalBrainInstance.ToBrainInstanceDTO();
            var reconstructed = dto.ToBrainInstance();

            Assert.That(reconstructed.BrainInstanceName, Is.EqualTo(originalBrainInstance.BrainInstanceName));
            Assert.That(reconstructed.WatchPositions, Is.EqualTo(originalBrainInstance.WatchPositions));
            Assert.That(reconstructed.UsageMin, Is.EqualTo(originalBrainInstance.UsageMin));
            Assert.That(reconstructed.MinimumInterest, Is.EqualTo(originalBrainInstance.MinimumInterest));

            // Test update functionality with validation
            var updateDTO = new BrainInstanceDTO
            {
                BrainInstanceName = "TestBrain",
                BrainLock = Guid.NewGuid(),
                LastSeen = DateTime.UtcNow
            };

            var updated = originalBrainInstance.UpdateBrainInstance(updateDTO);
            Assert.That(updated.BrainLock, Is.EqualTo(updateDTO.BrainLock));

            // Test invalid update (name mismatch)
            var invalidUpdateDTO = new BrainInstanceDTO
            {
                BrainInstanceName = "DifferentName",
                BrainLock = Guid.NewGuid()
            };

            Assert.Throws<ArgumentException>(() => originalBrainInstance.UpdateBrainInstance(invalidUpdateDTO));

            // Test batch transformations
            var brainInstances = new List<BrainInstance> { originalBrainInstance };
            var dtos = brainInstances.ToBrainInstanceDTOs();
            var reconstructedList = dtos.ToBrainInstances();

            Assert.That(reconstructedList.Count, Is.EqualTo(1));
            Assert.That(reconstructedList[0].BrainInstanceName, Is.EqualTo(originalBrainInstance.BrainInstanceName));

            // Test deep clone
            var cloned = originalBrainInstance.DeepClone();
            Assert.That(cloned.BrainInstanceName, Is.EqualTo(originalBrainInstance.BrainInstanceName));
            Assert.That(cloned, Is.Not.SameAs(originalBrainInstance));

            var clonedDTO = dto.DeepClone();
            Assert.That(clonedDTO.BrainInstanceName, Is.EqualTo(dto.BrainInstanceName));
            Assert.That(clonedDTO, Is.Not.SameAs(dto));

            // Test performance metrics collection
            var metrics = BrainInstanceExtensions.GetPerformanceMetrics();
            Assert.That(metrics, Is.Not.Null);
            Assert.That(metrics.ContainsKey("ToBrainInstanceDTO"), Is.True);
        }

        /// <summary>
        /// Tests CandlestickExtensions for null parameter validation and transformation accuracy.
        /// </summary>
        [Test]
        public void TestCandlestickExtensions()
        {
            // Test null parameter validation
            Assert.Throws<ArgumentNullException>(() => ((Candlestick)null).ToCandlestickDTO());
            Assert.Throws<ArgumentNullException>(() => ((CandlestickDTO)null).ToCandlestick());
            Assert.Throws<ArgumentNullException>(() => ((Candlestick)null).UpdateCandlestick(new CandlestickDTO()));
            Assert.Throws<ArgumentNullException>(() => new Candlestick().UpdateCandlestick(null));

            // Test transformation accuracy
            var originalCandlestick = new Candlestick
            {
                market_ticker = "TEST_MARKET",
                interval_type = 1, // 1 minute interval
                end_period_ts = 1640995200,
                end_period_datetime_utc = DateTime.UtcNow,
                year = 2022,
                month = 1,
                day = 1,
                hour = 12,
                minute = 0,
                open_interest = 1000,
                price_close = 5050, // Price * 100 to avoid decimals
                price_high = 5100,
                price_low = 4950,
                price_mean = 5025,
                price_open = 5000,
                price_previous = 4980,
                volume = 500,
                yes_ask_close = 5060,
                yes_ask_high = 5110,
                yes_ask_low = 4960,
                yes_ask_open = 5010,
                yes_bid_close = 5040,
                yes_bid_high = 5090,
                yes_bid_low = 4940,
                yes_bid_open = 4990
            };

            var dto = originalCandlestick.ToCandlestickDTO();
            var reconstructed = dto.ToCandlestick();

            Assert.That(reconstructed.market_ticker, Is.EqualTo(originalCandlestick.market_ticker));
            Assert.That(reconstructed.interval_type, Is.EqualTo(originalCandlestick.interval_type));
            Assert.That(reconstructed.end_period_ts, Is.EqualTo(originalCandlestick.end_period_ts));
            Assert.That(reconstructed.price_close, Is.EqualTo(originalCandlestick.price_close));
            Assert.That(reconstructed.volume, Is.EqualTo(originalCandlestick.volume));

            // Test update functionality with validation
            var updateDTO = new CandlestickDTO
            {
                market_ticker = "TEST_MARKET",
                interval_type = 1,
                end_period_ts = 1640995200,
                price_close = 5100,
                volume = 600
            };

            var updated = originalCandlestick.UpdateCandlestick(updateDTO);
            Assert.That(updated.price_close, Is.EqualTo(5100));
            Assert.That(updated.volume, Is.EqualTo(600));

            // Test invalid update (market ticker mismatch)
            var invalidUpdateDTO = new CandlestickDTO
            {
                market_ticker = "DIFFERENT_MARKET",
                interval_type = 1,
                end_period_ts = 1640995200
            };

            Assert.Throws<ArgumentException>(() => originalCandlestick.UpdateCandlestick(invalidUpdateDTO));

            // Test batch transformations
            var candlesticks = new List<Candlestick> { originalCandlestick };
            var dtos = candlesticks.ToCandlestickDTOs();
            var reconstructedList = dtos.ToCandlesticks();

            Assert.That(reconstructedList.Count, Is.EqualTo(1));
            Assert.That(reconstructedList[0].market_ticker, Is.EqualTo(originalCandlestick.market_ticker));

            // Test deep clone
            var cloned = originalCandlestick.DeepClone();
            Assert.That(cloned.market_ticker, Is.EqualTo(originalCandlestick.market_ticker));
            Assert.That(cloned, Is.Not.SameAs(originalCandlestick));

            var clonedDTO = dto.DeepClone();
            Assert.That(clonedDTO.market_ticker, Is.EqualTo(dto.market_ticker));
            Assert.That(clonedDTO, Is.Not.SameAs(dto));

            // Test performance metrics collection
            var metrics = CandlestickExtensions.GetPerformanceMetrics();
            Assert.That(metrics, Is.Not.Null);
            Assert.That(metrics.ContainsKey("ToCandlestickDTO"), Is.True);
        }

        #endregion

        /// <summary>
        /// Tests EventExtensions for null parameter validation and transformation accuracy.
        /// </summary>
        [Test]
        public void TestEventExtensions()
        {
            // Test null parameter validation
            Assert.Throws<ArgumentNullException>(() => ((Event)null).ToEventDTO());
            Assert.Throws<ArgumentNullException>(() => ((EventDTO)null).ToEvent());
            Assert.Throws<ArgumentNullException>(() => ((Event)null).UpdateEvent(new EventDTO()));
            Assert.Throws<ArgumentNullException>(() => new Event { event_ticker = "test", series_ticker = "test", title = "test", collateral_return_type = "binary", category = "test" }.UpdateEvent(null));

            // Test transformation accuracy
            var originalEvent = new Event
            {
                event_ticker = "TEST_EVENT",
                series_ticker = "TEST_SERIES",
                title = "Test Event",
                sub_title = "Test Subtitle",
                collateral_return_type = "binary",
                mutually_exclusive = true,
                category = "Test Category",
                CreatedDate = DateTime.UtcNow.AddDays(-1),
                LastModifiedDate = DateTime.UtcNow.AddDays(-1)
            };

            var dto = originalEvent.ToEventDTO();
            var reconstructed = dto.ToEvent();

            Assert.That(reconstructed.event_ticker, Is.EqualTo(originalEvent.event_ticker));
            Assert.That(reconstructed.series_ticker, Is.EqualTo(originalEvent.series_ticker));
            Assert.That(reconstructed.title, Is.EqualTo(originalEvent.title));
            Assert.That(reconstructed.category, Is.EqualTo(originalEvent.category));

            // Test update functionality
            var updateDTO = new EventDTO
            {
                event_ticker = "TEST_EVENT",
                series_ticker = "UPDATED_SERIES",
                title = "Updated Event",
                sub_title = "Updated Subtitle",
                collateral_return_type = "multi",
                mutually_exclusive = false,
                category = "Updated Category",
                CreatedDate = originalEvent.CreatedDate,
                LastModifiedDate = originalEvent.LastModifiedDate
            };

            var updated = originalEvent.UpdateEvent(updateDTO);
            Assert.That(updated.title, Is.EqualTo("Updated Event"));
            Assert.That(updated.category, Is.EqualTo("Updated Category"));
            Assert.That(updated.CreatedDate, Is.EqualTo(originalEvent.CreatedDate)); // Should not be updated

            // Test invalid update (ticker mismatch)
            var invalidUpdateDTO = new EventDTO
            {
                event_ticker = "DIFFERENT_EVENT",
                title = "Different Event"
            };

            Assert.Throws<ArgumentException>(() => originalEvent.UpdateEvent(invalidUpdateDTO));

            // Test batch transformations
            var events = new List<Event> { originalEvent };
            var dtos = events.ToEventDTOs();
            var reconstructedList = dtos.ToEvents();

            Assert.That(reconstructedList.Count, Is.EqualTo(1));
            Assert.That(reconstructedList[0].event_ticker, Is.EqualTo(originalEvent.event_ticker));

            // Test deep clone
            var cloned = originalEvent.DeepClone();
            Assert.That(cloned.event_ticker, Is.EqualTo(originalEvent.event_ticker));
            Assert.That(cloned, Is.Not.SameAs(originalEvent));

            var clonedDTO = dto.DeepClone();
            Assert.That(clonedDTO.event_ticker, Is.EqualTo(dto.event_ticker));
            Assert.That(clonedDTO, Is.Not.SameAs(dto));

            // Test performance metrics collection
            var metrics = EventExtensions.GetPerformanceMetrics();
            Assert.That(metrics, Is.Not.Null);
            Assert.That(metrics.ContainsKey("ToEventDTO"), Is.True);
        }

        /// <summary>
        /// Tests the Relative Strength Index (RSI) calculation accuracy across multiple scenarios.
        /// RSI measures price momentum on a 0-100 scale, with values above 70 indicating overbought
        /// conditions and below 30 indicating oversold conditions.
        /// </summary>
        /// <remarks>
        /// This test validates the RSI calculation using both synthetic and real market data scenarios.
        /// The test ensures the calculation handles edge cases and produces results within acceptable
        /// tolerance margins for floating-point precision.
        /// </remarks>
        [Test]
        public void TestRSICalculation()
        {
            foreach (var scenario in TradingMetricScenarios.GetRSIScenarios())
            {
                // Arrange
                var candlesticks = scenario.Candlesticks.TakeLast(13 + 1).ToList();
                Console.WriteLine($"Scenario: {scenario.Name}, Candlesticks Count: {candlesticks.Count}, Periods: 13");
                Console.WriteLine($"Prices: [{string.Join(", ", candlesticks.Select(c => c.MidClose))}]");

                // Act
                var rsi = _tradingCalculator.CalculateRSI(candlesticks, 13);
                Console.WriteLine($"Calculated RSI: {rsi}");

                // Assert
                if (!scenario.ExpectedRSI.HasValue)
                    throw new InvalidOperationException($"{scenario.Name}: Expected RSI value is null");
                var expected = scenario.ExpectedRSI.Value;
                var absoluteDiff = Math.Abs((decimal)(rsi - expected));
                var percentageDiff = expected != 0 ? (absoluteDiff / Math.Abs((decimal)(scenario.ExpectedRSI.Value))) * 100 : absoluteDiff;
                Console.WriteLine($"{scenario.Name}: RSI Percentage Difference: {(expected != 0 ? $"{percentageDiff:F6}%" : $"Absolute Diff: {absoluteDiff:F6}")}");
                var margin = _marginFactor * Math.Abs(scenario.ExpectedRSI.Value);
                Assert.That(rsi, Is.EqualTo((double)scenario.ExpectedRSI.Value).Within(margin), $"{scenario.Name}: RSI mismatch. Expected: {expected}, Actual: {rsi}");
            }
        }

        /// <summary>
        /// Tests the Moving Average Convergence Divergence (MACD) calculation accuracy.
        /// MACD shows the relationship between two moving averages and includes a signal line
        /// and histogram for trading signals.
        /// </summary>
        /// <remarks>
        /// Validates MACD line, signal line, and histogram calculations using comprehensive
        /// test scenarios with expected values.
        /// </remarks>
        [Test]
        public void TestMACDCalculation()
        {
            foreach (var scenario in TradingMetricScenarios.GetMACDScenarios())
            {
                // Arrange
                var candlesticks = scenario.Candlesticks; // Use full 34 candlesticks for MACD

                // Act
                var (macdLine, signalLine, histogram) = _tradingCalculator.CalculateMACD(candlesticks, 12, 26, 9);

                // Assert
                if (!scenario.ExpectedMACD.macdLine.HasValue || !scenario.ExpectedMACD.signalLine.HasValue || !scenario.ExpectedMACD.histogram.HasValue)
                    throw new InvalidOperationException($"{scenario.Name}: Expected MACD values contain null");

                var expectedMacd = scenario.ExpectedMACD.macdLine.Value;
                var macdDiff = Math.Abs((decimal)(macdLine - expectedMacd));
                var macdPercentageDiff = expectedMacd != 0 ? (macdDiff / Math.Abs((decimal)(scenario.ExpectedMACD.macdLine.Value))) * 100 : macdDiff;
                Console.WriteLine($"{scenario.Name}: MACD Line Percentage Difference: {(expectedMacd != 0 ? $"{macdPercentageDiff:F6}%" : $"Absolute Diff: {macdDiff:F6}")}");
                var macdMargin = _marginFactor * Math.Abs(scenario.ExpectedMACD.macdLine.Value);
                Assert.That(macdLine, Is.EqualTo((double)scenario.ExpectedMACD.macdLine.Value).Within(macdMargin), $"{scenario.Name}: MACD Line mismatch");

                var expectedSignal = scenario.ExpectedMACD.signalLine.Value;
                var signalDiff = Math.Abs((decimal)(signalLine - expectedSignal));
                var signalPercentageDiff = expectedSignal != 0 ? (signalDiff / Math.Abs((decimal)(scenario.ExpectedMACD.signalLine.Value))) * 100 : signalDiff;
                Console.WriteLine($"{scenario.Name}: Signal Line Percentage Difference: {(expectedSignal != 0 ? $"{signalPercentageDiff:F6}%" : $"Absolute Diff: {signalDiff:F6}")}");
                var signalMargin = _marginFactor * Math.Abs(scenario.ExpectedMACD.signalLine.Value);
                Assert.That(signalLine, Is.EqualTo((double)scenario.ExpectedMACD.signalLine.Value).Within(signalMargin), $"{scenario.Name}: Signal Line mismatch");

                var expectedHistogram = scenario.ExpectedMACD.histogram.Value;
                var histogramDiff = Math.Abs((decimal)(histogram - expectedHistogram));
                var histogramPercentageDiff = expectedHistogram != 0 ? (histogramDiff / Math.Abs((decimal)(scenario.ExpectedMACD.histogram.Value))) * 100 : histogramDiff;
                Console.WriteLine($"{scenario.Name}: Histogram Percentage Difference: {(expectedHistogram != 0 ? $"{histogramPercentageDiff:F6}%" : $"Absolute Diff: {histogramDiff:F6}")}");
                var histogramMargin = _marginFactor * Math.Abs(scenario.ExpectedMACD.histogram.Value);
                Assert.That(histogram, Is.EqualTo((double)scenario.ExpectedMACD.histogram.Value).Within(histogramMargin), $"{scenario.Name}: Histogram mismatch");
            }
        }

        /// <summary>
        /// Tests the Exponential Moving Average (EMA) calculation accuracy.
        /// EMA gives more weight to recent prices, making it more responsive to price changes
        /// than simple moving averages.
        /// </summary>
        /// <remarks>
        /// Validates EMA calculations using test scenarios with expected values.
        /// </remarks>
        [Test]
        public void TestEMACalculation()
        {
            foreach (var scenario in TradingMetricScenarios.GetEMAScenarios())
            {
                // Arrange
                var candlesticks = scenario.Candlesticks; // Use 5 candlesticks from source

                // Act
                var result = TradingCalculations.CalculateEMA(candlesticks.Select(c => c.MidClose).ToList(), 5);

                // Assert
                if (!scenario.ExpectedEMA.HasValue)
                    throw new InvalidOperationException($"{scenario.Name}: Expected EMA value is null");
                var expected = scenario.ExpectedEMA.Value;
                var absoluteDiff = Math.Abs((decimal)(result - expected));
                var percentageDiff = expected != 0 ? (absoluteDiff / Math.Abs((decimal)(scenario.ExpectedEMA.Value))) * 100 : absoluteDiff;
                Console.WriteLine($"{scenario.Name}: EMA Percentage Difference: {(expected != 0 ? $"{percentageDiff:F6}%" : $"Absolute Diff: {absoluteDiff:F6}")}");
                var margin = _marginFactor * Math.Abs(scenario.ExpectedEMA.Value);
                Assert.That(result, Is.EqualTo((double)scenario.ExpectedEMA.Value).Within(margin), $"{scenario.Name}: EMA mismatch. Expected: {expected}, Actual: {result}");
            }
        }

        /// <summary>
        /// Tests the Bollinger Bands calculation accuracy.
        /// Bollinger Bands consist of a moving average and upper/lower bands based on standard deviation,
        /// used to identify volatility and potential price reversals.
        /// </summary>
        /// <remarks>
        /// Validates middle band (SMA), upper band, and lower band calculations.
        /// </remarks>
        [Test]
        public void TestBollingerBandsCalculation()
        {
            foreach (var scenario in TradingMetricScenarios.GetBollingerBandsScenarios())
            {
                // Arrange
                var candlesticks = scenario.Candlesticks; // Use full 14 candlesticks from source

                // Act
                var (middle, upper, lower) = _tradingCalculator.CalculateBollingerBands(candlesticks, 14, 2);

                // Assert
                if (!scenario.ExpectedBollingerBands.middle.HasValue || !scenario.ExpectedBollingerBands.upper.HasValue || !scenario.ExpectedBollingerBands.lower.HasValue)
                    throw new InvalidOperationException($"{scenario.Name}: Expected Bollinger Bands values contain null");

                var expectedMiddle = scenario.ExpectedBollingerBands.middle.Value;
                var middleDiff = Math.Abs((decimal)(middle - expectedMiddle));
                var middlePercentageDiff = expectedMiddle != 0 ? (middleDiff / Math.Abs((decimal)(scenario.ExpectedBollingerBands.middle.Value))) * 100 : middleDiff;
                Console.WriteLine($"{scenario.Name}: Middle Band Percentage Difference: {(expectedMiddle != 0 ? $"{middlePercentageDiff:F6}%" : $"Absolute Diff: {middleDiff:F6}")}");
                var middleMargin = _marginFactor * Math.Abs(scenario.ExpectedBollingerBands.middle.Value);
                Assert.That(middle, Is.EqualTo((double)scenario.ExpectedBollingerBands.middle.Value).Within(middleMargin), $"{scenario.Name}: Middle band mismatch");

                var expectedUpper = scenario.ExpectedBollingerBands.upper.Value;
                var upperDiff = Math.Abs((decimal)(upper - expectedUpper));
                var upperPercentageDiff = expectedUpper != 0 ? (upperDiff / Math.Abs((decimal)(scenario.ExpectedBollingerBands.upper.Value))) * 100 : upperDiff;
                Console.WriteLine($"{scenario.Name}: Upper Band Percentage Difference: {(expectedUpper != 0 ? $"{upperPercentageDiff:F6}%" : $"Absolute Diff: {upperDiff:F6}")}");
                var upperMargin = _marginFactor * Math.Abs(scenario.ExpectedBollingerBands.upper.Value);
                Assert.That(upper, Is.EqualTo((double)scenario.ExpectedBollingerBands.upper.Value).Within(upperMargin), $"{scenario.Name}: Upper band mismatch");

                var expectedLower = scenario.ExpectedBollingerBands.lower.Value;
                var lowerDiff = Math.Abs((decimal)(lower - expectedLower));
                var lowerPercentageDiff = expectedLower != 0 ? (lowerDiff / Math.Abs((decimal)(scenario.ExpectedBollingerBands.lower.Value))) * 100 : lowerDiff;
                Console.WriteLine($"{scenario.Name}: Lower Band Percentage Difference: {(expectedLower != 0 ? $"{lowerPercentageDiff:F6}%" : $"Absolute Diff: {lowerDiff:F6}")}");
                var lowerMargin = _marginFactor * Math.Abs(scenario.ExpectedBollingerBands.lower.Value);
                Assert.That(lower, Is.EqualTo((double)scenario.ExpectedBollingerBands.lower.Value).Within(lowerMargin), $"{scenario.Name}: Lower band mismatch");
            }
        }

        /// <summary>
        /// Tests the Average True Range (ATR) calculation accuracy.
        /// ATR measures volatility by calculating the average of true ranges over a period.
        /// Higher ATR values indicate higher volatility.
        /// </summary>
        /// <remarks>
        /// Validates ATR calculations using test scenarios with expected values.
        /// Uses one less than the full candlestick count for the period to account for historical data needs.
        /// </remarks>
        [Test]
        public void TestATRCalculation()
        {
            foreach (var scenario in TradingMetricScenarios.GetATRScenarios())
            {
                // Arrange
                var candlesticks = scenario.Candlesticks; // Use full 14 candlesticks from source

                // Act
                var result = _tradingCalculator.CalculateATR(candlesticks, 13); //Use one less than full number, it needs one more for history

                // Assert
                if (!scenario.ExpectedATR.HasValue)
                    throw new InvalidOperationException($"{scenario.Name}: Expected ATR value is null");
                var expected = scenario.ExpectedATR.Value;
                var absoluteDiff = Math.Abs((decimal)(result - expected));
                var percentageDiff = expected != 0 ? (absoluteDiff / Math.Abs((decimal)(scenario.ExpectedATR.Value))) * 100 : absoluteDiff;
                Console.WriteLine($"{scenario.Name}: ATR Percentage Difference: {(expected != 0 ? $"{percentageDiff:F6}%" : $"Absolute Diff: {absoluteDiff:F6}")}");
                var margin = _marginFactor * Math.Abs(scenario.ExpectedATR.Value);
                Assert.That(result, Is.EqualTo((double)scenario.ExpectedATR.Value).Within(margin), $"{scenario.Name}: ATR mismatch. Expected: {expected}, Actual: {result}");
            }
        }

        /// <summary>
        /// Tests the Volume Weighted Average Price (VWAP) calculation accuracy.
        /// VWAP represents the average price weighted by volume, commonly used as a benchmark
        /// for intraday trading performance.
        /// </summary>
        /// <remarks>
        /// Validates VWAP calculations using test scenarios with price and volume data.
        /// </remarks>
        [Test]
        public void TestVWAPCalculation()
        {
            foreach (var scenario in TradingMetricScenarios.GetVWAPScenarios())
            {
                // Arrange
                var candlesticks = scenario.Candlesticks; // Use full 17 candlesticks from source

                // Act
                var result = _tradingCalculator.CalculateVWAP(candlesticks, 17);

                // Assert
                if (!scenario.ExpectedVWAP.HasValue)
                    throw new InvalidOperationException($"{scenario.Name}: Expected VWAP value is null");
                var expected = scenario.ExpectedVWAP.Value;
                var absoluteDiff = Math.Abs((result.Value - (decimal)expected));
                var percentageDiff = expected != 0 ? (absoluteDiff / Math.Abs((decimal)(scenario.ExpectedVWAP.Value))) * 100 : absoluteDiff;
                Console.WriteLine($"{scenario.Name}: VWAP Percentage Difference: {(expected != 0 ? $"{percentageDiff:F6}%" : $"Absolute Diff: {absoluteDiff:F6}")}");
                var margin = _marginFactor * Math.Abs(scenario.ExpectedVWAP.Value);
                Assert.That(result, Is.EqualTo((double)scenario.ExpectedVWAP.Value).Within(margin), $"{scenario.Name}: VWAP mismatch. Expected: {expected}, Actual: {result}");
            }
        }

        /// <summary>
        /// Tests the Stochastic Oscillator calculation accuracy.
        /// Stochastic Oscillator compares a closing price to its price range over a period,
        /// with %K showing current close relative to range and %D being the moving average of %K.
        /// Values above 80 indicate overbought, below 20 indicate oversold conditions.
        /// </summary>
        /// <remarks>
        /// Validates both %K and %D calculations using test scenarios.
        /// </remarks>
        [Test]
        public void TestStochasticOscillatorCalculation()
        {
            foreach (var scenario in TradingMetricScenarios.GetStochasticScenarios())
            {
                // Arrange
                var candlesticks = scenario.Candlesticks; // Use full 17 candlesticks from source

                // Act
                var (kResult, dResult) = _tradingCalculator.CalculateStochastic(candlesticks, 14, 3);

                // Assert
                if (!scenario.ExpectedStochastic.k.HasValue)
                    throw new InvalidOperationException($"{scenario.Name}: Expected %K value is null");
                var expectedK = scenario.ExpectedStochastic.k.Value;
                var kDiff = Math.Abs((decimal)(kResult - expectedK));
                var kPercentageDiff = expectedK != 0 ? (kDiff / Math.Abs((decimal)(scenario.ExpectedStochastic.k.Value))) * 100 : kDiff;
                Console.WriteLine($"{scenario.Name}: %K Percentage Difference: {(expectedK != 0 ? $"{kPercentageDiff:F6}%" : $"Absolute Diff: {kDiff:F6}")}");
                var kMargin = _marginFactor * Math.Abs(scenario.ExpectedStochastic.k.Value);
                Assert.That(kResult, Is.EqualTo((double)scenario.ExpectedStochastic.k.Value).Within(kMargin), $"{scenario.Name}: %K mismatch");

                var dMargin = scenario.ExpectedStochastic.d.HasValue ? _marginFactor * Math.Abs(scenario.ExpectedStochastic.d.Value) : 0;
                if (scenario.ExpectedStochastic.d.HasValue)
                {
                    var expectedD = scenario.ExpectedStochastic.d.Value;
                    var dDiff = Math.Abs(dResult.GetValueOrDefault() - expectedD);
                    var dPercentageDiff = expectedD != 0 ? (dDiff / Math.Abs(scenario.ExpectedStochastic.d.Value)) * 100 : dDiff;
                    Console.WriteLine($"{scenario.Name}: %D Percentage Difference: {(expectedD != 0 ? $"{dPercentageDiff:F6}%" : $"Absolute Diff: {dDiff:F6}")}");
                }
                Assert.That(dResult, Is.EqualTo(scenario.ExpectedStochastic.d.HasValue ? (double)scenario.ExpectedStochastic.d.Value : null).Within(dMargin).Or.Null, $"{scenario.Name}: %D mismatch");
            }
        }

        /// <summary>
        /// Tests the On-Balance Volume (OBV) calculation accuracy.
        /// OBV accumulates volume based on price direction - volume is added when price closes higher,
        /// subtracted when lower. Rising OBV indicates buying pressure, falling indicates selling pressure.
        /// </summary>
        /// <remarks>
        /// Validates OBV calculations using test scenarios with price and volume data.
        /// OBV is a cumulative indicator that can be positive or negative based on net volume flow.
        /// </remarks>
        [Test]
        public void TestOBVCalculation()
        {
            foreach (var scenario in TradingMetricScenarios.GetOBVScenarios())
            {
                // Arrange
                var candlesticks = scenario.Candlesticks; // Use full 10 candlesticks from source

                // Act
                var result = _tradingCalculator.CalculateOBV(candlesticks);

                // Assert
                Assert.That(result, Is.EqualTo(scenario.ExpectedOBV), $"{scenario.Name}: OBV mismatch. Expected: {scenario.ExpectedOBV}, Actual: {result}");
            }
        }
    }
}
