USE [kalshibot-dev]
GO
/****** Object:  StoredProcedure [dbo].[sp_InsertUpdateMarket]    Script Date: 1/30/2025 8:29:41 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER PROCEDURE [dbo].[sp_InsertUpdateMarket]
    @market_ticker             VARCHAR(150),
    @event_ticker              VARCHAR(50),
    @market_type               VARCHAR(20),
    @title                     VARCHAR(255),
    @subtitle                  VARCHAR(255) = NULL,
    @yes_sub_title             VARCHAR(50),
    @no_sub_title              VARCHAR(50),
    @open_time                 DATETIME,
    @close_time                DATETIME,
    @expected_expiration_time  DATETIME,
    @expiration_time           DATETIME,
    @latest_expiration_time    DATETIME,
    @settlement_timer_seconds  INT,
    @status                    VARCHAR(20),
    @response_price_units      VARCHAR(20),
    @notional_value            INT,
    @tick_size                 INT,
    @yes_bid                   INT,
    @yes_ask                   INT,
    @no_bid                    INT,
    @no_ask                    INT,
    @last_price                INT,
    @previous_yes_bid          INT,
    @previous_yes_ask          INT,
    @previous_price            INT,
    @volume                    INT,
    @volume_24h                INT,
    @liquidity                 INT,
    @open_interest             INT,
    @result                    VARCHAR(20),
    @can_close_early           BIT,
    @expiration_value          VARCHAR(50),
    @category                  VARCHAR(50),
    @risk_limit_cents          INT,
    @strike_type               VARCHAR(30),
    @floor_strike              INT = NULL,
    @rules_primary             VARCHAR(255),
    @rules_secondary           VARCHAR(255)
AS
BEGIN
    SET NOCOUNT ON;

    MERGE INTO dbo.t_Markets AS target
    USING (SELECT
               @market_ticker AS market_ticker,
               @event_ticker AS event_ticker,
               @market_type AS market_type,
               @title AS title,
               @subtitle AS subtitle,
               @yes_sub_title AS yes_sub_title,
               @no_sub_title AS no_sub_title,
               @open_time AS open_time,
               @close_time AS close_time,
               @expected_expiration_time AS expected_expiration_time,
               @expiration_time AS expiration_time,
               @latest_expiration_time AS latest_expiration_time,
               @settlement_timer_seconds AS settlement_timer_seconds,
               @status AS status,
               @response_price_units AS response_price_units,
               @notional_value AS notional_value,
               @tick_size AS tick_size,
               @yes_bid AS yes_bid,
               @yes_ask AS yes_ask,
               @no_bid AS no_bid,
               @no_ask AS no_ask,
               @last_price AS last_price,
               @previous_yes_bid AS previous_yes_bid,
               @previous_yes_ask AS previous_yes_ask,
               @previous_price AS previous_price,
               @volume AS volume,
               @volume_24h AS volume_24h,
               @liquidity AS liquidity,
               @open_interest AS open_interest,
               @result AS result,
               @can_close_early AS can_close_early,
               @expiration_value AS expiration_value,
               @category AS category,
               @risk_limit_cents AS risk_limit_cents,
               @strike_type AS strike_type,
               @floor_strike AS floor_strike,
               @rules_primary AS rules_primary,
               @rules_secondary AS rules_secondary
           ) AS source
    ON target.market_ticker = source.market_ticker
    WHEN MATCHED THEN
        UPDATE SET
            event_ticker = source.event_ticker,
            market_type = source.market_type,
            title = case when source.title <> '' then source.title else target.title end,
            subtitle = source.subtitle,
            yes_sub_title = source.yes_sub_title,
            no_sub_title = source.no_sub_title,
            open_time = source.open_time,
            close_time = source.close_time,
            expected_expiration_time = source.expected_expiration_time,
            expiration_time = source.expiration_time,
            latest_expiration_time = source.latest_expiration_time,
            settlement_timer_seconds = source.settlement_timer_seconds,
            status = source.status,
            response_price_units = source.response_price_units,
            notional_value = source.notional_value,
            tick_size = source.tick_size,
            yes_bid = source.yes_bid,
            yes_ask = source.yes_ask,
            no_bid = source.no_bid,
            no_ask = source.no_ask,
            last_price = source.last_price,
            previous_yes_bid = source.previous_yes_bid,
            previous_yes_ask = source.previous_yes_ask,
            previous_price = source.previous_price,
            volume = source.volume,
            volume_24h = source.volume_24h,
            liquidity = source.liquidity,
            open_interest = source.open_interest,
            result = source.result,
            can_close_early = source.can_close_early,
            expiration_value = source.expiration_value,
            category = source.category,
            risk_limit_cents = source.risk_limit_cents,
            strike_type = source.strike_type,
            floor_strike = source.floor_strike,
            rules_primary = source.rules_primary,
            rules_secondary = source.rules_secondary
    WHEN NOT MATCHED BY TARGET THEN
        INSERT (market_ticker, event_ticker, market_type, title, subtitle, yes_sub_title, no_sub_title, open_time, close_time, expected_expiration_time,
                expiration_time, latest_expiration_time, settlement_timer_seconds, status, response_price_units, notional_value, tick_size, yes_bid, yes_ask,
                no_bid, no_ask, last_price, previous_yes_bid, previous_yes_ask, previous_price, volume, volume_24h, liquidity, open_interest, result, can_close_early,
                expiration_value, category, risk_limit_cents, strike_type, floor_strike, rules_primary, rules_secondary)
        VALUES (source.market_ticker, source.event_ticker, source.market_type, source.title, source.subtitle, source.yes_sub_title, source.no_sub_title, source.open_time,
                source.close_time, source.expected_expiration_time, source.expiration_time, source.latest_expiration_time, source.settlement_timer_seconds, source.status,
                source.response_price_units, source.notional_value, source.tick_size, source.yes_bid, source.yes_ask, source.no_bid, source.no_ask, source.last_price,
                source.previous_yes_bid, source.previous_yes_ask, source.previous_price, source.volume, source.volume_24h, source.liquidity, source.open_interest,
                source.result, source.can_close_early, source.expiration_value, source.category, source.risk_limit_cents, source.strike_type, source.floor_strike,
                source.rules_primary, source.rules_secondary);
END;
