namespace TradingSimulator.Strategies
{
    /// <summary>
    /// Represents a trading decision generated by a trading strategy evaluation.
    /// This class encapsulates the signals, metadata, and finality status of a decision
    /// made during backtesting or live trading simulation. It serves as the primary
    /// output container for strategy logic, allowing strategies to communicate
    /// actionable insights and supplementary information to the trading engine.
    /// </summary>
    public class TradingDecision
    {
        /// <summary>
        /// Gets or sets the collection of trading signals generated by the strategy.
        /// Each signal is represented as a key-value pair where the key is the signal
        /// name (e.g., "PriceRise", "PriceDrop") and the value is a numeric strength
        /// or confidence level (typically 0.0 to 1.0, where 1.0 indicates strong signal).
        /// These signals are used by the trading engine to determine the appropriate
        /// trading action (Buy, Sell, or Hold).
        /// </summary>
        public Dictionary<string, double> Signals { get; set; } = new Dictionary<string, double>();

        /// <summary>
        /// Gets or sets the collection of additional metadata associated with the decision.
        /// This can include supplementary information such as confidence scores,
        /// risk metrics, strategy-specific parameters, or debugging information
        /// that may be useful for analysis or logging purposes.
        /// </summary>
        public Dictionary<string, object> Metadata { get; set; } = new Dictionary<string, object>();

        /// <summary>
        /// Gets or sets a value indicating whether this decision is final and actionable.
        /// When true, the decision contains valid signals that should be processed
        /// by the trading engine. When false, the decision may be incomplete or
        /// under evaluation, and should not trigger trading actions.
        /// </summary>
        public bool IsFinal { get; set; }

        /// <summary>
        /// Adds or updates a trading signal in the Signals collection.
        /// This method provides a convenient way to populate the decision with
        /// signal data during strategy evaluation.
        /// </summary>
        /// <param name="key">The name of the signal (e.g., "PriceRise").</param>
        /// <param name="value">The strength or value of the signal.</param>
        public void AddSignal(string key, double value) => Signals[key] = value;

        /// <summary>
        /// Adds or updates metadata in the Metadata collection.
        /// This method allows strategies to attach supplementary information
        /// to the decision for analysis, logging, or further processing.
        /// </summary>
        /// <param name="key">The name of the metadata item.</param>
        /// <param name="value">The value of the metadata item.</param>
        public void AddMetadata(string key, object value) => Metadata[key] = value;
    }
}
