namespace TradingSimulator.Strategies
{
    /// <summary>
    /// Represents a trading decision generated by a trading strategy evaluation.
    /// This class encapsulates the signals, metadata, and finality status of a decision
    /// made during backtesting or live trading simulation. It serves as the primary
    /// output container for strategy logic, allowing strategies to communicate
    /// actionable insights and supplementary information to the trading engine.
    /// </summary>
    public class TradingDecision
    {
        /// <summary>
        /// Gets or sets the collection of trading signals generated by the strategy.
        /// Each signal is represented as a key-value pair where the key is the signal
        /// name (e.g., "PriceRise", "PriceDrop") and the value is a numeric strength
        /// or confidence level (typically 0.0 to 1.0, where 1.0 indicates strong signal).
        /// These signals are used by the trading engine to determine the appropriate
        /// trading action (Buy, Sell, or Hold).
        /// </summary>
        public Dictionary<string, double> Signals { get; set; } = new Dictionary<string, double>();

        /// <summary>
        /// Gets or sets the collection of additional metadata associated with the decision.
        /// This can include supplementary information such as confidence scores,
        /// risk metrics, strategy-specific parameters, or debugging information
        /// that may be useful for analysis or logging purposes.
        /// </summary>
        public Dictionary<string, object> Metadata { get; set; } = new Dictionary<string, object>();

        /// <summary>
        /// Gets or sets a value indicating whether this decision is final and actionable.
        /// When true, the decision contains valid signals that should be processed
        /// by the trading engine. When false, the decision may be incomplete or
        /// under evaluation, and should not trigger trading actions.
        /// </summary>
        public bool IsFinal { get; set; }

        /// <summary>
        /// Adds or updates a trading signal in the Signals collection.
        /// This method provides a convenient way to populate the decision with
        /// signal data during strategy evaluation.
        /// </summary>
        /// <param name="key">The name of the signal (e.g., "PriceRise").</param>
        /// <param name="value">The strength or value of the signal (0.0 to 1.0).</param>
        public void AddSignal(string key, double value)
        {
            if (string.IsNullOrEmpty(key))
                throw new ArgumentException("Key cannot be null or empty.", nameof(key));
            if (value < 0.0 || value > 1.0)
                throw new ArgumentOutOfRangeException(nameof(value), "Signal value must be between 0.0 and 1.0.");
            Signals[key] = value;
        }

        /// <summary>
        /// Adds or updates metadata in the Metadata collection.
        /// This method allows strategies to attach supplementary information
        /// to the decision for analysis, logging, or further processing.
        /// </summary>
        /// <param name="key">The name of the metadata item.</param>
        /// <param name="value">The value of the metadata item.</param>
        public void AddMetadata(string key, object value)
        {
            if (string.IsNullOrEmpty(key))
                throw new ArgumentException("Key cannot be null or empty.", nameof(key));
            if (value == null)
                throw new ArgumentNullException(nameof(value), "Value cannot be null.");
            Metadata[key] = value;
        }

        /// <summary>
        /// Creates a deep copy of the TradingDecision instance.
        /// </summary>
        /// <returns>A new TradingDecision with copied signals and metadata.</returns>
        public TradingDecision Clone()
        {
            var clone = new TradingDecision
            {
                IsFinal = this.IsFinal,
                Signals = new Dictionary<string, double>(this.Signals),
                Metadata = new Dictionary<string, object>(this.Metadata)
            };
            return clone;
        }

        /// <summary>
        /// Normalizes all signal values to be within the 0.0 to 1.0 range.
        /// Values below 0.0 are set to 0.0, values above 1.0 are set to 1.0.
        /// </summary>
        public void NormalizeSignals()
        {
            foreach (var key in Signals.Keys.ToList())
            {
                double value = Signals[key];
                if (value < 0.0) value = 0.0;
                else if (value > 1.0) value = 1.0;
                Signals[key] = value;
            }
        }
    }
}
